node .\program.js generate-config -r Account -o output
node .\program.js generate-config -r ActivityDefinition -o output
node .\program.js generate-config -r AdverseEvent -o output
node .\program.js generate-config -r AllergyIntolerance -o output
node .\program.js generate-config -r Appointment -o output
node .\program.js generate-config -r AppointmentResponse -o output
node .\program.js generate-config -r AuditEvent -o output
node .\program.js generate-config -r Basic -o output
node .\program.js generate-config -r Binary -o output
node .\program.js generate-config -r BiologicallyDerivedProduct -o output
node .\program.js generate-config -r BodyStructure -o output
node .\program.js generate-config -r CapabilityStatement -o output
node .\program.js generate-config -r CarePlan -o output
node .\program.js generate-config -r CareTeam -o output
node .\program.js generate-config -r CatalogEntry -o output
node .\program.js generate-config -r ChargeItem -o output
node .\program.js generate-config -r ChargeItemDefinition -o output
node .\program.js generate-config -r Claim -o output
node .\program.js generate-config -r ClaimResponse -o output
node .\program.js generate-config -r ClinicalImpression -o output
node .\program.js generate-config -r CodeSystem -o output
node .\program.js generate-config -r Communication -o output
node .\program.js generate-config -r CommunicationRequest -o output
node .\program.js generate-config -r CompartmentDefinition -o output
node .\program.js generate-config -r Composition -o output
node .\program.js generate-config -r ConceptMap -o output
node .\program.js generate-config -r Condition -o output
node .\program.js generate-config -r Consent -o output
node .\program.js generate-config -r Contract -o output
node .\program.js generate-config -r Coverage -o output
node .\program.js generate-config -r CoverageEligibilityRequest -o output
node .\program.js generate-config -r CoverageEligibilityResponse -o output
node .\program.js generate-config -r DetectedIssue -o output
node .\program.js generate-config -r Device -o output
node .\program.js generate-config -r DeviceDefinition -o output
node .\program.js generate-config -r DeviceMetric -o output
node .\program.js generate-config -r DeviceRequest -o output
node .\program.js generate-config -r DeviceUseStatement -o output
node .\program.js generate-config -r DiagnosticReport -o output
node .\program.js generate-config -r DocumentManifest -o output
node .\program.js generate-config -r DocumentReference -o output
node .\program.js generate-config -r EffectEvidenceSynthesis -o output
node .\program.js generate-config -r Encounter -o output
node .\program.js generate-config -r Endpoint -o output
node .\program.js generate-config -r EnrollmentRequest -o output
node .\program.js generate-config -r EnrollmentResponse -o output
node .\program.js generate-config -r EpisodeOfCare -o output
node .\program.js generate-config -r EventDefinition -o output
node .\program.js generate-config -r Evidence -o output
node .\program.js generate-config -r EvidenceVariable -o output
node .\program.js generate-config -r ExampleScenario -o output
node .\program.js generate-config -r ExplanationOfBenefit -o output
node .\program.js generate-config -r FamilyMemberHistory -o output
node .\program.js generate-config -r Flag -o output
node .\program.js generate-config -r Goal -o output
node .\program.js generate-config -r GraphDefinition -o output
node .\program.js generate-config -r Group -o output
node .\program.js generate-config -r GuidanceResponse -o output
node .\program.js generate-config -r HealthcareService -o output
node .\program.js generate-config -r ImagingStudy -o output
node .\program.js generate-config -r Immunization -o output
node .\program.js generate-config -r ImmunizationEvaluation -o output
node .\program.js generate-config -r ImmunizationRecommendation -o output
node .\program.js generate-config -r ImplementationGuide -o output
node .\program.js generate-config -r InsurancePlan -o output
node .\program.js generate-config -r Invoice -o output
node .\program.js generate-config -r Library -o output
node .\program.js generate-config -r Linkage -o output
node .\program.js generate-config -r List -o output
node .\program.js generate-config -r Location -o output
node .\program.js generate-config -r Measure -o output
node .\program.js generate-config -r MeasureReport -o output
node .\program.js generate-config -r Media -o output
node .\program.js generate-config -r Medication -o output
node .\program.js generate-config -r MedicationAdministration -o output
node .\program.js generate-config -r MedicationDispense -o output
node .\program.js generate-config -r MedicationKnowledge -o output
node .\program.js generate-config -r MedicationRequest -o output
node .\program.js generate-config -r MedicationStatement -o output
node .\program.js generate-config -r MedicinalProduct -o output
node .\program.js generate-config -r MedicinalProductAuthorization -o output
node .\program.js generate-config -r MedicinalProductContraindication -o output
node .\program.js generate-config -r MedicinalProductIndication -o output
node .\program.js generate-config -r MedicinalProductIngredient -o output
node .\program.js generate-config -r MedicinalProductInteraction -o output
node .\program.js generate-config -r MedicinalProductManufactured -o output
node .\program.js generate-config -r MedicinalProductPackaged -o output
node .\program.js generate-config -r MedicinalProductPharmaceutical -o output
node .\program.js generate-config -r MedicinalProductUndesirableEffect -o output
node .\program.js generate-config -r MessageDefinition -o output
node .\program.js generate-config -r MessageHeader -o output
node .\program.js generate-config -r MolecularSequence -o output
node .\program.js generate-config -r NamingSystem -o output
node .\program.js generate-config -r NutritionOrder -o output
node .\program.js generate-config -r Observation -o output
node .\program.js generate-config -r ObservationDefinition -o output
node .\program.js generate-config -r OperationDefinition -o output
node .\program.js generate-config -r OperationOutcome -o output
node .\program.js generate-config -r Organization -o output
node .\program.js generate-config -r OrganizationAffiliation -o output
node .\program.js generate-config -r Patient -o output
node .\program.js generate-config -r PaymentNotice -o output
node .\program.js generate-config -r PaymentReconciliation -o output
node .\program.js generate-config -r Person -o output
node .\program.js generate-config -r PlanDefinition -o output
node .\program.js generate-config -r Practitioner -o output
node .\program.js generate-config -r PractitionerRole -o output
node .\program.js generate-config -r Procedure -o output
node .\program.js generate-config -r Provenance -o output
node .\program.js generate-config -r Questionnaire -o output
node .\program.js generate-config -r QuestionnaireResponse -o output
node .\program.js generate-config -r RelatedPerson -o output
node .\program.js generate-config -r RequestGroup -o output
node .\program.js generate-config -r ResearchDefinition -o output
node .\program.js generate-config -r ResearchElementDefinition -o output
node .\program.js generate-config -r ResearchStudy -o output
node .\program.js generate-config -r ResearchSubject -o output
node .\program.js generate-config -r RiskAssessment -o output
node .\program.js generate-config -r RiskEvidenceSynthesis -o output
node .\program.js generate-config -r Schedule -o output
node .\program.js generate-config -r SearchParameter -o output
node .\program.js generate-config -r ServiceRequest -o output
node .\program.js generate-config -r Slot -o output
node .\program.js generate-config -r Specimen -o output
node .\program.js generate-config -r SpecimenDefinition -o output
node .\program.js generate-config -r StructureDefinition -o output
node .\program.js generate-config -r StructureMap -o output
node .\program.js generate-config -r Subscription -o output
node .\program.js generate-config -r Substance -o output
node .\program.js generate-config -r SubstanceNucleicAcid -o output
node .\program.js generate-config -r SubstancePolymer -o output
node .\program.js generate-config -r SubstanceProtein -o output
node .\program.js generate-config -r SubstanceReferenceInformation -o output
node .\program.js generate-config -r SubstanceSourceMaterial -o output
node .\program.js generate-config -r SubstanceSpecification -o output
node .\program.js generate-config -r SupplyDelivery -o output
node .\program.js generate-config -r SupplyRequest -o output
node .\program.js generate-config -r Task -o output
node .\program.js generate-config -r TerminologyCapabilities -o output
node .\program.js generate-config -r TestReport -o output
node .\program.js generate-config -r TestScript -o output
node .\program.js generate-config -r ValueSet -o output
node .\program.js generate-config -r VerificationResult -o output
node .\program.js generate-config -r VisionPrescription -o output
