Identifier:
 propertiesByDefault: 
  - type
  - system
  - value
 customProperties:
  - path: assigner
    type: array

Patient_Contact:
 propertiesByDefault: 
  - relationship
  - name
  - telecom
  - address
  - gender
  - organization
  - period