trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  testProjects: "**/*Test/*.csproj"
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build Engine Core
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

