trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  testProjects: "**/*Test/*.csproj"
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build Engine Core
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
  displayName: 'Run CredScan'
  inputs:
    outputFormat: sarif
    debugMode: false
  continueOnError: true

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: RoslynAnalyzers@2
  inputs:
    userProvideBuildInfo: 'auto'
