CREATE EXTERNAL TABLE [fhir].[Binary] (
    [resourceType] NVARCHAR(4000),
    [id] VARCHAR(64),
    [meta.id] NVARCHAR(100),
    [meta.extension] NVARCHAR(MAX),
    [meta.versionId] VARCHAR(64),
    [meta.lastUpdated] VARCHAR(64),
    [meta.source] VARCHAR(256),
    [meta.profile] VARCHAR(MAX),
    [meta.security] VARCHAR(MAX),
    [meta.tag] VARCHAR(MAX),
    [implicitRules] VARCHAR(256),
    [language] NVARCHAR(100),
    [contentType] NVARCHAR(100),
    [securityContext.id] NVARCHAR(100),
    [securityContext.extension] NVARCHAR(MAX),
    [securityContext.reference] NVARCHAR(4000),
    [securityContext.type] VARCHAR(256),
    [securityContext.identifier.id] NVARCHAR(100),
    [securityContext.identifier.extension] NVARCHAR(MAX),
    [securityContext.identifier.use] NVARCHAR(64),
    [securityContext.identifier.type] NVARCHAR(MAX),
    [securityContext.identifier.system] VARCHAR(256),
    [securityContext.identifier.value] NVARCHAR(4000),
    [securityContext.identifier.period] NVARCHAR(MAX),
    [securityContext.identifier.assigner] NVARCHAR(MAX),
    [securityContext.display] NVARCHAR(4000),
    [data] NVARCHAR(MAX),
) WITH (
    LOCATION='/Binary/**',
    DATA_SOURCE = ParquetSource,
    FILE_FORMAT = ParquetFormat
);
