CREATE EXTERNAL TABLE [fhir].[SubstanceSpecification] (
    [resourceType] NVARCHAR(4000),
    [id] VARCHAR(64),
    [meta.id] NVARCHAR(4000),
    [meta.extension] NVARCHAR(MAX),
    [meta.versionId] VARCHAR(64),
    [meta.lastUpdated] VARCHAR(30),
    [meta.source] VARCHAR(256),
    [meta.profile] VARCHAR(MAX),
    [meta.security] VARCHAR(MAX),
    [meta.tag] VARCHAR(MAX),
    [implicitRules] VARCHAR(256),
    [language] NVARCHAR(4000),
    [text.id] NVARCHAR(4000),
    [text.extension] NVARCHAR(MAX),
    [text.status] NVARCHAR(64),
    [text.div] NVARCHAR(MAX),
    [extension] NVARCHAR(MAX),
    [modifierExtension] NVARCHAR(MAX),
    [identifier.id] NVARCHAR(4000),
    [identifier.extension] NVARCHAR(MAX),
    [identifier.use] NVARCHAR(64),
    [identifier.type.id] NVARCHAR(4000),
    [identifier.type.extension] NVARCHAR(MAX),
    [identifier.type.coding] NVARCHAR(MAX),
    [identifier.type.text] NVARCHAR(4000),
    [identifier.system] VARCHAR(256),
    [identifier.value] NVARCHAR(4000),
    [identifier.period.id] NVARCHAR(4000),
    [identifier.period.extension] NVARCHAR(MAX),
    [identifier.period.start] VARCHAR(30),
    [identifier.period.end] VARCHAR(30),
    [identifier.assigner.id] NVARCHAR(4000),
    [identifier.assigner.extension] NVARCHAR(MAX),
    [identifier.assigner.reference] NVARCHAR(4000),
    [identifier.assigner.type] VARCHAR(256),
    [identifier.assigner.identifier] NVARCHAR(MAX),
    [identifier.assigner.display] NVARCHAR(4000),
    [type.id] NVARCHAR(4000),
    [type.extension] NVARCHAR(MAX),
    [type.coding] VARCHAR(MAX),
    [type.text] NVARCHAR(4000),
    [status.id] NVARCHAR(4000),
    [status.extension] NVARCHAR(MAX),
    [status.coding] VARCHAR(MAX),
    [status.text] NVARCHAR(4000),
    [domain.id] NVARCHAR(4000),
    [domain.extension] NVARCHAR(MAX),
    [domain.coding] VARCHAR(MAX),
    [domain.text] NVARCHAR(4000),
    [description] NVARCHAR(4000),
    [source] VARCHAR(MAX),
    [comment] NVARCHAR(4000),
    [moiety] VARCHAR(MAX),
    [property] VARCHAR(MAX),
    [referenceInformation.id] NVARCHAR(4000),
    [referenceInformation.extension] NVARCHAR(MAX),
    [referenceInformation.reference] NVARCHAR(4000),
    [referenceInformation.type] VARCHAR(256),
    [referenceInformation.identifier.id] NVARCHAR(4000),
    [referenceInformation.identifier.extension] NVARCHAR(MAX),
    [referenceInformation.identifier.use] NVARCHAR(64),
    [referenceInformation.identifier.type] NVARCHAR(MAX),
    [referenceInformation.identifier.system] VARCHAR(256),
    [referenceInformation.identifier.value] NVARCHAR(4000),
    [referenceInformation.identifier.period] NVARCHAR(MAX),
    [referenceInformation.identifier.assigner] NVARCHAR(MAX),
    [referenceInformation.display] NVARCHAR(4000),
    [structure.id] NVARCHAR(4000),
    [structure.extension] NVARCHAR(MAX),
    [structure.modifierExtension] NVARCHAR(MAX),
    [structure.stereochemistry.id] NVARCHAR(4000),
    [structure.stereochemistry.extension] NVARCHAR(MAX),
    [structure.stereochemistry.coding] NVARCHAR(MAX),
    [structure.stereochemistry.text] NVARCHAR(4000),
    [structure.opticalActivity.id] NVARCHAR(4000),
    [structure.opticalActivity.extension] NVARCHAR(MAX),
    [structure.opticalActivity.coding] NVARCHAR(MAX),
    [structure.opticalActivity.text] NVARCHAR(4000),
    [structure.molecularFormula] NVARCHAR(4000),
    [structure.molecularFormulaByMoiety] NVARCHAR(4000),
    [structure.isotope] VARCHAR(MAX),
    [structure.molecularWeight.id] NVARCHAR(4000),
    [structure.molecularWeight.extension] NVARCHAR(MAX),
    [structure.molecularWeight.modifierExtension] NVARCHAR(MAX),
    [structure.molecularWeight.method] NVARCHAR(MAX),
    [structure.molecularWeight.type] NVARCHAR(MAX),
    [structure.molecularWeight.amount] NVARCHAR(MAX),
    [structure.source] VARCHAR(MAX),
    [structure.representation] VARCHAR(MAX),
    [code] VARCHAR(MAX),
    [name] VARCHAR(MAX),
    [molecularWeight] VARCHAR(MAX),
    [relationship] VARCHAR(MAX),
    [nucleicAcid.id] NVARCHAR(4000),
    [nucleicAcid.extension] NVARCHAR(MAX),
    [nucleicAcid.reference] NVARCHAR(4000),
    [nucleicAcid.type] VARCHAR(256),
    [nucleicAcid.identifier.id] NVARCHAR(4000),
    [nucleicAcid.identifier.extension] NVARCHAR(MAX),
    [nucleicAcid.identifier.use] NVARCHAR(64),
    [nucleicAcid.identifier.type] NVARCHAR(MAX),
    [nucleicAcid.identifier.system] VARCHAR(256),
    [nucleicAcid.identifier.value] NVARCHAR(4000),
    [nucleicAcid.identifier.period] NVARCHAR(MAX),
    [nucleicAcid.identifier.assigner] NVARCHAR(MAX),
    [nucleicAcid.display] NVARCHAR(4000),
    [polymer.id] NVARCHAR(4000),
    [polymer.extension] NVARCHAR(MAX),
    [polymer.reference] NVARCHAR(4000),
    [polymer.type] VARCHAR(256),
    [polymer.identifier.id] NVARCHAR(4000),
    [polymer.identifier.extension] NVARCHAR(MAX),
    [polymer.identifier.use] NVARCHAR(64),
    [polymer.identifier.type] NVARCHAR(MAX),
    [polymer.identifier.system] VARCHAR(256),
    [polymer.identifier.value] NVARCHAR(4000),
    [polymer.identifier.period] NVARCHAR(MAX),
    [polymer.identifier.assigner] NVARCHAR(MAX),
    [polymer.display] NVARCHAR(4000),
    [protein.id] NVARCHAR(4000),
    [protein.extension] NVARCHAR(MAX),
    [protein.reference] NVARCHAR(4000),
    [protein.type] VARCHAR(256),
    [protein.identifier.id] NVARCHAR(4000),
    [protein.identifier.extension] NVARCHAR(MAX),
    [protein.identifier.use] NVARCHAR(64),
    [protein.identifier.type] NVARCHAR(MAX),
    [protein.identifier.system] VARCHAR(256),
    [protein.identifier.value] NVARCHAR(4000),
    [protein.identifier.period] NVARCHAR(MAX),
    [protein.identifier.assigner] NVARCHAR(MAX),
    [protein.display] NVARCHAR(4000),
    [sourceMaterial.id] NVARCHAR(4000),
    [sourceMaterial.extension] NVARCHAR(MAX),
    [sourceMaterial.reference] NVARCHAR(4000),
    [sourceMaterial.type] VARCHAR(256),
    [sourceMaterial.identifier.id] NVARCHAR(4000),
    [sourceMaterial.identifier.extension] NVARCHAR(MAX),
    [sourceMaterial.identifier.use] NVARCHAR(64),
    [sourceMaterial.identifier.type] NVARCHAR(MAX),
    [sourceMaterial.identifier.system] VARCHAR(256),
    [sourceMaterial.identifier.value] NVARCHAR(4000),
    [sourceMaterial.identifier.period] NVARCHAR(MAX),
    [sourceMaterial.identifier.assigner] NVARCHAR(MAX),
    [sourceMaterial.display] NVARCHAR(4000),
) WITH (
    LOCATION='/SubstanceSpecification/**',
    DATA_SOURCE = ParquetSource,
    FILE_FORMAT = ParquetFormat
);

GO

CREATE VIEW fhir.SubstanceSpecificationSource AS
SELECT
    [id],
    [source.JSON],
    [source.id],
    [source.extension],
    [source.reference],
    [source.type],
    [source.identifier.id],
    [source.identifier.extension],
    [source.identifier.use],
    [source.identifier.type],
    [source.identifier.system],
    [source.identifier.value],
    [source.identifier.period],
    [source.identifier.assigner],
    [source.display]
FROM openrowset (
        BULK 'SubstanceSpecification/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [source.JSON]  VARCHAR(MAX) '$.source'
    ) AS rowset
    CROSS APPLY openjson (rowset.[source.JSON]) with (
        [source.id]                    NVARCHAR(4000)      '$.id',
        [source.extension]             NVARCHAR(MAX)       '$.extension',
        [source.reference]             NVARCHAR(4000)      '$.reference',
        [source.type]                  VARCHAR(256)        '$.type',
        [source.identifier.id]         NVARCHAR(4000)      '$.identifier.id',
        [source.identifier.extension]  NVARCHAR(MAX)       '$.identifier.extension',
        [source.identifier.use]        NVARCHAR(64)        '$.identifier.use',
        [source.identifier.type]       NVARCHAR(MAX)       '$.identifier.type',
        [source.identifier.system]     VARCHAR(256)        '$.identifier.system',
        [source.identifier.value]      NVARCHAR(4000)      '$.identifier.value',
        [source.identifier.period]     NVARCHAR(MAX)       '$.identifier.period',
        [source.identifier.assigner]   NVARCHAR(MAX)       '$.identifier.assigner',
        [source.display]               NVARCHAR(4000)      '$.display'
    ) j

GO

CREATE VIEW fhir.SubstanceSpecificationMoiety AS
SELECT
    [id],
    [moiety.JSON],
    [moiety.id],
    [moiety.extension],
    [moiety.modifierExtension],
    [moiety.role.id],
    [moiety.role.extension],
    [moiety.role.coding],
    [moiety.role.text],
    [moiety.identifier.id],
    [moiety.identifier.extension],
    [moiety.identifier.use],
    [moiety.identifier.type],
    [moiety.identifier.system],
    [moiety.identifier.value],
    [moiety.identifier.period],
    [moiety.identifier.assigner],
    [moiety.name],
    [moiety.stereochemistry.id],
    [moiety.stereochemistry.extension],
    [moiety.stereochemistry.coding],
    [moiety.stereochemistry.text],
    [moiety.opticalActivity.id],
    [moiety.opticalActivity.extension],
    [moiety.opticalActivity.coding],
    [moiety.opticalActivity.text],
    [moiety.molecularFormula],
    [moiety.amount.Quantity.id],
    [moiety.amount.Quantity.extension],
    [moiety.amount.Quantity.value],
    [moiety.amount.Quantity.comparator],
    [moiety.amount.Quantity.unit],
    [moiety.amount.Quantity.system],
    [moiety.amount.Quantity.code],
    [moiety.amount.string]
FROM openrowset (
        BULK 'SubstanceSpecification/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [moiety.JSON]  VARCHAR(MAX) '$.moiety'
    ) AS rowset
    CROSS APPLY openjson (rowset.[moiety.JSON]) with (
        [moiety.id]                    NVARCHAR(4000)      '$.id',
        [moiety.extension]             NVARCHAR(MAX)       '$.extension',
        [moiety.modifierExtension]     NVARCHAR(MAX)       '$.modifierExtension',
        [moiety.role.id]               NVARCHAR(4000)      '$.role.id',
        [moiety.role.extension]        NVARCHAR(MAX)       '$.role.extension',
        [moiety.role.coding]           NVARCHAR(MAX)       '$.role.coding',
        [moiety.role.text]             NVARCHAR(4000)      '$.role.text',
        [moiety.identifier.id]         NVARCHAR(4000)      '$.identifier.id',
        [moiety.identifier.extension]  NVARCHAR(MAX)       '$.identifier.extension',
        [moiety.identifier.use]        NVARCHAR(64)        '$.identifier.use',
        [moiety.identifier.type]       NVARCHAR(MAX)       '$.identifier.type',
        [moiety.identifier.system]     VARCHAR(256)        '$.identifier.system',
        [moiety.identifier.value]      NVARCHAR(4000)      '$.identifier.value',
        [moiety.identifier.period]     NVARCHAR(MAX)       '$.identifier.period',
        [moiety.identifier.assigner]   NVARCHAR(MAX)       '$.identifier.assigner',
        [moiety.name]                  NVARCHAR(4000)      '$.name',
        [moiety.stereochemistry.id]    NVARCHAR(4000)      '$.stereochemistry.id',
        [moiety.stereochemistry.extension] NVARCHAR(MAX)       '$.stereochemistry.extension',
        [moiety.stereochemistry.coding] NVARCHAR(MAX)       '$.stereochemistry.coding',
        [moiety.stereochemistry.text]  NVARCHAR(4000)      '$.stereochemistry.text',
        [moiety.opticalActivity.id]    NVARCHAR(4000)      '$.opticalActivity.id',
        [moiety.opticalActivity.extension] NVARCHAR(MAX)       '$.opticalActivity.extension',
        [moiety.opticalActivity.coding] NVARCHAR(MAX)       '$.opticalActivity.coding',
        [moiety.opticalActivity.text]  NVARCHAR(4000)      '$.opticalActivity.text',
        [moiety.molecularFormula]      NVARCHAR(4000)      '$.molecularFormula',
        [moiety.amount.Quantity.id]    NVARCHAR(4000)      '$.amount.Quantity.id',
        [moiety.amount.Quantity.extension] NVARCHAR(MAX)       '$.amount.Quantity.extension',
        [moiety.amount.Quantity.value] float               '$.amount.Quantity.value',
        [moiety.amount.Quantity.comparator] NVARCHAR(64)        '$.amount.Quantity.comparator',
        [moiety.amount.Quantity.unit]  NVARCHAR(4000)      '$.amount.Quantity.unit',
        [moiety.amount.Quantity.system] VARCHAR(256)        '$.amount.Quantity.system',
        [moiety.amount.Quantity.code]  NVARCHAR(4000)      '$.amount.Quantity.code',
        [moiety.amount.string]         NVARCHAR(4000)      '$.amount.string'
    ) j

GO

CREATE VIEW fhir.SubstanceSpecificationProperty AS
SELECT
    [id],
    [property.JSON],
    [property.id],
    [property.extension],
    [property.modifierExtension],
    [property.category.id],
    [property.category.extension],
    [property.category.coding],
    [property.category.text],
    [property.code.id],
    [property.code.extension],
    [property.code.coding],
    [property.code.text],
    [property.parameters],
    [property.definingSubstance.Reference.id],
    [property.definingSubstance.Reference.extension],
    [property.definingSubstance.Reference.reference],
    [property.definingSubstance.Reference.type],
    [property.definingSubstance.Reference.identifier],
    [property.definingSubstance.Reference.display],
    [property.definingSubstance.CodeableConcept.id],
    [property.definingSubstance.CodeableConcept.extension],
    [property.definingSubstance.CodeableConcept.coding],
    [property.definingSubstance.CodeableConcept.text],
    [property.amount.Quantity.id],
    [property.amount.Quantity.extension],
    [property.amount.Quantity.value],
    [property.amount.Quantity.comparator],
    [property.amount.Quantity.unit],
    [property.amount.Quantity.system],
    [property.amount.Quantity.code],
    [property.amount.string]
FROM openrowset (
        BULK 'SubstanceSpecification/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [property.JSON]  VARCHAR(MAX) '$.property'
    ) AS rowset
    CROSS APPLY openjson (rowset.[property.JSON]) with (
        [property.id]                  NVARCHAR(4000)      '$.id',
        [property.extension]           NVARCHAR(MAX)       '$.extension',
        [property.modifierExtension]   NVARCHAR(MAX)       '$.modifierExtension',
        [property.category.id]         NVARCHAR(4000)      '$.category.id',
        [property.category.extension]  NVARCHAR(MAX)       '$.category.extension',
        [property.category.coding]     NVARCHAR(MAX)       '$.category.coding',
        [property.category.text]       NVARCHAR(4000)      '$.category.text',
        [property.code.id]             NVARCHAR(4000)      '$.code.id',
        [property.code.extension]      NVARCHAR(MAX)       '$.code.extension',
        [property.code.coding]         NVARCHAR(MAX)       '$.code.coding',
        [property.code.text]           NVARCHAR(4000)      '$.code.text',
        [property.parameters]          NVARCHAR(4000)      '$.parameters',
        [property.definingSubstance.Reference.id] NVARCHAR(4000)      '$.definingSubstance.Reference.id',
        [property.definingSubstance.Reference.extension] NVARCHAR(MAX)       '$.definingSubstance.Reference.extension',
        [property.definingSubstance.Reference.reference] NVARCHAR(4000)      '$.definingSubstance.Reference.reference',
        [property.definingSubstance.Reference.type] VARCHAR(256)        '$.definingSubstance.Reference.type',
        [property.definingSubstance.Reference.identifier] NVARCHAR(MAX)       '$.definingSubstance.Reference.identifier',
        [property.definingSubstance.Reference.display] NVARCHAR(4000)      '$.definingSubstance.Reference.display',
        [property.definingSubstance.CodeableConcept.id] NVARCHAR(4000)      '$.definingSubstance.CodeableConcept.id',
        [property.definingSubstance.CodeableConcept.extension] NVARCHAR(MAX)       '$.definingSubstance.CodeableConcept.extension',
        [property.definingSubstance.CodeableConcept.coding] NVARCHAR(MAX)       '$.definingSubstance.CodeableConcept.coding',
        [property.definingSubstance.CodeableConcept.text] NVARCHAR(4000)      '$.definingSubstance.CodeableConcept.text',
        [property.amount.Quantity.id]  NVARCHAR(4000)      '$.amount.Quantity.id',
        [property.amount.Quantity.extension] NVARCHAR(MAX)       '$.amount.Quantity.extension',
        [property.amount.Quantity.value] float               '$.amount.Quantity.value',
        [property.amount.Quantity.comparator] NVARCHAR(64)        '$.amount.Quantity.comparator',
        [property.amount.Quantity.unit] NVARCHAR(4000)      '$.amount.Quantity.unit',
        [property.amount.Quantity.system] VARCHAR(256)        '$.amount.Quantity.system',
        [property.amount.Quantity.code] NVARCHAR(4000)      '$.amount.Quantity.code',
        [property.amount.string]       NVARCHAR(4000)      '$.amount.string'
    ) j

GO

CREATE VIEW fhir.SubstanceSpecificationCode AS
SELECT
    [id],
    [code.JSON],
    [code.id],
    [code.extension],
    [code.modifierExtension],
    [code.code.id],
    [code.code.extension],
    [code.code.coding],
    [code.code.text],
    [code.status.id],
    [code.status.extension],
    [code.status.coding],
    [code.status.text],
    [code.statusDate],
    [code.comment],
    [code.source]
FROM openrowset (
        BULK 'SubstanceSpecification/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [code.JSON]  VARCHAR(MAX) '$.code'
    ) AS rowset
    CROSS APPLY openjson (rowset.[code.JSON]) with (
        [code.id]                      NVARCHAR(4000)      '$.id',
        [code.extension]               NVARCHAR(MAX)       '$.extension',
        [code.modifierExtension]       NVARCHAR(MAX)       '$.modifierExtension',
        [code.code.id]                 NVARCHAR(4000)      '$.code.id',
        [code.code.extension]          NVARCHAR(MAX)       '$.code.extension',
        [code.code.coding]             NVARCHAR(MAX)       '$.code.coding',
        [code.code.text]               NVARCHAR(4000)      '$.code.text',
        [code.status.id]               NVARCHAR(4000)      '$.status.id',
        [code.status.extension]        NVARCHAR(MAX)       '$.status.extension',
        [code.status.coding]           NVARCHAR(MAX)       '$.status.coding',
        [code.status.text]             NVARCHAR(4000)      '$.status.text',
        [code.statusDate]              VARCHAR(30)         '$.statusDate',
        [code.comment]                 NVARCHAR(4000)      '$.comment',
        [code.source]                  NVARCHAR(MAX)       '$.source' AS JSON
    ) j

GO

CREATE VIEW fhir.SubstanceSpecificationName AS
SELECT
    [id],
    [name.JSON],
    [name.id],
    [name.extension],
    [name.modifierExtension],
    [name.name],
    [name.type.id],
    [name.type.extension],
    [name.type.coding],
    [name.type.text],
    [name.status.id],
    [name.status.extension],
    [name.status.coding],
    [name.status.text],
    [name.preferred],
    [name.language],
    [name.domain],
    [name.jurisdiction],
    [name.synonym],
    [name.translation],
    [name.official],
    [name.source]
FROM openrowset (
        BULK 'SubstanceSpecification/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [name.JSON]  VARCHAR(MAX) '$.name'
    ) AS rowset
    CROSS APPLY openjson (rowset.[name.JSON]) with (
        [name.id]                      NVARCHAR(4000)      '$.id',
        [name.extension]               NVARCHAR(MAX)       '$.extension',
        [name.modifierExtension]       NVARCHAR(MAX)       '$.modifierExtension',
        [name.name]                    NVARCHAR(4000)      '$.name',
        [name.type.id]                 NVARCHAR(4000)      '$.type.id',
        [name.type.extension]          NVARCHAR(MAX)       '$.type.extension',
        [name.type.coding]             NVARCHAR(MAX)       '$.type.coding',
        [name.type.text]               NVARCHAR(4000)      '$.type.text',
        [name.status.id]               NVARCHAR(4000)      '$.status.id',
        [name.status.extension]        NVARCHAR(MAX)       '$.status.extension',
        [name.status.coding]           NVARCHAR(MAX)       '$.status.coding',
        [name.status.text]             NVARCHAR(4000)      '$.status.text',
        [name.preferred]               bit                 '$.preferred',
        [name.language]                NVARCHAR(MAX)       '$.language' AS JSON,
        [name.domain]                  NVARCHAR(MAX)       '$.domain' AS JSON,
        [name.jurisdiction]            NVARCHAR(MAX)       '$.jurisdiction' AS JSON,
        [name.synonym]                 NVARCHAR(MAX)       '$.synonym' AS JSON,
        [name.translation]             NVARCHAR(MAX)       '$.translation' AS JSON,
        [name.official]                NVARCHAR(MAX)       '$.official' AS JSON,
        [name.source]                  NVARCHAR(MAX)       '$.source' AS JSON
    ) j

GO

CREATE VIEW fhir.SubstanceSpecificationMolecularWeight AS
SELECT
    [id],
    [molecularWeight.JSON],
    [molecularWeight.id],
    [molecularWeight.extension],
    [molecularWeight.modifierExtension],
    [molecularWeight.method.id],
    [molecularWeight.method.extension],
    [molecularWeight.method.coding],
    [molecularWeight.method.text],
    [molecularWeight.type.id],
    [molecularWeight.type.extension],
    [molecularWeight.type.coding],
    [molecularWeight.type.text],
    [molecularWeight.amount.id],
    [molecularWeight.amount.extension],
    [molecularWeight.amount.value],
    [molecularWeight.amount.comparator],
    [molecularWeight.amount.unit],
    [molecularWeight.amount.system],
    [molecularWeight.amount.code]
FROM openrowset (
        BULK 'SubstanceSpecification/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [molecularWeight.JSON]  VARCHAR(MAX) '$.molecularWeight'
    ) AS rowset
    CROSS APPLY openjson (rowset.[molecularWeight.JSON]) with (
        [molecularWeight.id]           NVARCHAR(4000)      '$.id',
        [molecularWeight.extension]    NVARCHAR(MAX)       '$.extension',
        [molecularWeight.modifierExtension] NVARCHAR(MAX)       '$.modifierExtension',
        [molecularWeight.method.id]    NVARCHAR(4000)      '$.method.id',
        [molecularWeight.method.extension] NVARCHAR(MAX)       '$.method.extension',
        [molecularWeight.method.coding] NVARCHAR(MAX)       '$.method.coding',
        [molecularWeight.method.text]  NVARCHAR(4000)      '$.method.text',
        [molecularWeight.type.id]      NVARCHAR(4000)      '$.type.id',
        [molecularWeight.type.extension] NVARCHAR(MAX)       '$.type.extension',
        [molecularWeight.type.coding]  NVARCHAR(MAX)       '$.type.coding',
        [molecularWeight.type.text]    NVARCHAR(4000)      '$.type.text',
        [molecularWeight.amount.id]    NVARCHAR(4000)      '$.amount.id',
        [molecularWeight.amount.extension] NVARCHAR(MAX)       '$.amount.extension',
        [molecularWeight.amount.value] float               '$.amount.value',
        [molecularWeight.amount.comparator] NVARCHAR(64)        '$.amount.comparator',
        [molecularWeight.amount.unit]  NVARCHAR(4000)      '$.amount.unit',
        [molecularWeight.amount.system] VARCHAR(256)        '$.amount.system',
        [molecularWeight.amount.code]  NVARCHAR(4000)      '$.amount.code'
    ) j

GO

CREATE VIEW fhir.SubstanceSpecificationRelationship AS
SELECT
    [id],
    [relationship.JSON],
    [relationship.id],
    [relationship.extension],
    [relationship.modifierExtension],
    [relationship.relationship.id],
    [relationship.relationship.extension],
    [relationship.relationship.coding],
    [relationship.relationship.text],
    [relationship.isDefining],
    [relationship.amountRatioLowLimit.id],
    [relationship.amountRatioLowLimit.extension],
    [relationship.amountRatioLowLimit.numerator],
    [relationship.amountRatioLowLimit.denominator],
    [relationship.amountType.id],
    [relationship.amountType.extension],
    [relationship.amountType.coding],
    [relationship.amountType.text],
    [relationship.source],
    [relationship.substance.Reference.id],
    [relationship.substance.Reference.extension],
    [relationship.substance.Reference.reference],
    [relationship.substance.Reference.type],
    [relationship.substance.Reference.identifier],
    [relationship.substance.Reference.display],
    [relationship.substance.CodeableConcept.id],
    [relationship.substance.CodeableConcept.extension],
    [relationship.substance.CodeableConcept.coding],
    [relationship.substance.CodeableConcept.text],
    [relationship.amount.Quantity.id],
    [relationship.amount.Quantity.extension],
    [relationship.amount.Quantity.value],
    [relationship.amount.Quantity.comparator],
    [relationship.amount.Quantity.unit],
    [relationship.amount.Quantity.system],
    [relationship.amount.Quantity.code],
    [relationship.amount.Range.id],
    [relationship.amount.Range.extension],
    [relationship.amount.Range.low],
    [relationship.amount.Range.high],
    [relationship.amount.Ratio.id],
    [relationship.amount.Ratio.extension],
    [relationship.amount.Ratio.numerator],
    [relationship.amount.Ratio.denominator],
    [relationship.amount.string]
FROM openrowset (
        BULK 'SubstanceSpecification/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [relationship.JSON]  VARCHAR(MAX) '$.relationship'
    ) AS rowset
    CROSS APPLY openjson (rowset.[relationship.JSON]) with (
        [relationship.id]              NVARCHAR(4000)      '$.id',
        [relationship.extension]       NVARCHAR(MAX)       '$.extension',
        [relationship.modifierExtension] NVARCHAR(MAX)       '$.modifierExtension',
        [relationship.relationship.id] NVARCHAR(4000)      '$.relationship.id',
        [relationship.relationship.extension] NVARCHAR(MAX)       '$.relationship.extension',
        [relationship.relationship.coding] NVARCHAR(MAX)       '$.relationship.coding',
        [relationship.relationship.text] NVARCHAR(4000)      '$.relationship.text',
        [relationship.isDefining]      bit                 '$.isDefining',
        [relationship.amountRatioLowLimit.id] NVARCHAR(4000)      '$.amountRatioLowLimit.id',
        [relationship.amountRatioLowLimit.extension] NVARCHAR(MAX)       '$.amountRatioLowLimit.extension',
        [relationship.amountRatioLowLimit.numerator] NVARCHAR(MAX)       '$.amountRatioLowLimit.numerator',
        [relationship.amountRatioLowLimit.denominator] NVARCHAR(MAX)       '$.amountRatioLowLimit.denominator',
        [relationship.amountType.id]   NVARCHAR(4000)      '$.amountType.id',
        [relationship.amountType.extension] NVARCHAR(MAX)       '$.amountType.extension',
        [relationship.amountType.coding] NVARCHAR(MAX)       '$.amountType.coding',
        [relationship.amountType.text] NVARCHAR(4000)      '$.amountType.text',
        [relationship.source]          NVARCHAR(MAX)       '$.source' AS JSON,
        [relationship.substance.Reference.id] NVARCHAR(4000)      '$.substance.Reference.id',
        [relationship.substance.Reference.extension] NVARCHAR(MAX)       '$.substance.Reference.extension',
        [relationship.substance.Reference.reference] NVARCHAR(4000)      '$.substance.Reference.reference',
        [relationship.substance.Reference.type] VARCHAR(256)        '$.substance.Reference.type',
        [relationship.substance.Reference.identifier] NVARCHAR(MAX)       '$.substance.Reference.identifier',
        [relationship.substance.Reference.display] NVARCHAR(4000)      '$.substance.Reference.display',
        [relationship.substance.CodeableConcept.id] NVARCHAR(4000)      '$.substance.CodeableConcept.id',
        [relationship.substance.CodeableConcept.extension] NVARCHAR(MAX)       '$.substance.CodeableConcept.extension',
        [relationship.substance.CodeableConcept.coding] NVARCHAR(MAX)       '$.substance.CodeableConcept.coding',
        [relationship.substance.CodeableConcept.text] NVARCHAR(4000)      '$.substance.CodeableConcept.text',
        [relationship.amount.Quantity.id] NVARCHAR(4000)      '$.amount.Quantity.id',
        [relationship.amount.Quantity.extension] NVARCHAR(MAX)       '$.amount.Quantity.extension',
        [relationship.amount.Quantity.value] float               '$.amount.Quantity.value',
        [relationship.amount.Quantity.comparator] NVARCHAR(64)        '$.amount.Quantity.comparator',
        [relationship.amount.Quantity.unit] NVARCHAR(4000)      '$.amount.Quantity.unit',
        [relationship.amount.Quantity.system] VARCHAR(256)        '$.amount.Quantity.system',
        [relationship.amount.Quantity.code] NVARCHAR(4000)      '$.amount.Quantity.code',
        [relationship.amount.Range.id] NVARCHAR(4000)      '$.amount.Range.id',
        [relationship.amount.Range.extension] NVARCHAR(MAX)       '$.amount.Range.extension',
        [relationship.amount.Range.low] NVARCHAR(MAX)       '$.amount.Range.low',
        [relationship.amount.Range.high] NVARCHAR(MAX)       '$.amount.Range.high',
        [relationship.amount.Ratio.id] NVARCHAR(4000)      '$.amount.Ratio.id',
        [relationship.amount.Ratio.extension] NVARCHAR(MAX)       '$.amount.Ratio.extension',
        [relationship.amount.Ratio.numerator] NVARCHAR(MAX)       '$.amount.Ratio.numerator',
        [relationship.amount.Ratio.denominator] NVARCHAR(MAX)       '$.amount.Ratio.denominator',
        [relationship.amount.string]   NVARCHAR(4000)      '$.amount.string'
    ) j
