CREATE EXTERNAL TABLE [fhir].[Task] (
    [resourceType] NVARCHAR(4000),
    [id] VARCHAR(64),
    [meta.id] NVARCHAR(100),
    [meta.extension] NVARCHAR(MAX),
    [meta.versionId] VARCHAR(64),
    [meta.lastUpdated] VARCHAR(64),
    [meta.source] VARCHAR(256),
    [meta.profile] VARCHAR(MAX),
    [meta.security] VARCHAR(MAX),
    [meta.tag] VARCHAR(MAX),
    [implicitRules] VARCHAR(256),
    [language] NVARCHAR(100),
    [text.id] NVARCHAR(100),
    [text.extension] NVARCHAR(MAX),
    [text.status] NVARCHAR(64),
    [text.div] NVARCHAR(MAX),
    [extension] NVARCHAR(MAX),
    [modifierExtension] NVARCHAR(MAX),
    [identifier] VARCHAR(MAX),
    [instantiatesCanonical] VARCHAR(256),
    [instantiatesUri] VARCHAR(256),
    [basedOn] VARCHAR(MAX),
    [groupIdentifier.id] NVARCHAR(100),
    [groupIdentifier.extension] NVARCHAR(MAX),
    [groupIdentifier.use] NVARCHAR(64),
    [groupIdentifier.type.id] NVARCHAR(100),
    [groupIdentifier.type.extension] NVARCHAR(MAX),
    [groupIdentifier.type.coding] NVARCHAR(MAX),
    [groupIdentifier.type.text] NVARCHAR(4000),
    [groupIdentifier.system] VARCHAR(256),
    [groupIdentifier.value] NVARCHAR(4000),
    [groupIdentifier.period.id] NVARCHAR(100),
    [groupIdentifier.period.extension] NVARCHAR(MAX),
    [groupIdentifier.period.start] VARCHAR(64),
    [groupIdentifier.period.end] VARCHAR(64),
    [groupIdentifier.assigner.id] NVARCHAR(100),
    [groupIdentifier.assigner.extension] NVARCHAR(MAX),
    [groupIdentifier.assigner.reference] NVARCHAR(4000),
    [groupIdentifier.assigner.type] VARCHAR(256),
    [groupIdentifier.assigner.identifier] NVARCHAR(MAX),
    [groupIdentifier.assigner.display] NVARCHAR(4000),
    [partOf] VARCHAR(MAX),
    [status] NVARCHAR(64),
    [statusReason.id] NVARCHAR(100),
    [statusReason.extension] NVARCHAR(MAX),
    [statusReason.coding] VARCHAR(MAX),
    [statusReason.text] NVARCHAR(4000),
    [businessStatus.id] NVARCHAR(100),
    [businessStatus.extension] NVARCHAR(MAX),
    [businessStatus.coding] VARCHAR(MAX),
    [businessStatus.text] NVARCHAR(4000),
    [intent] NVARCHAR(64),
    [priority] NVARCHAR(100),
    [code.id] NVARCHAR(100),
    [code.extension] NVARCHAR(MAX),
    [code.coding] VARCHAR(MAX),
    [code.text] NVARCHAR(4000),
    [description] NVARCHAR(4000),
    [focus.id] NVARCHAR(100),
    [focus.extension] NVARCHAR(MAX),
    [focus.reference] NVARCHAR(4000),
    [focus.type] VARCHAR(256),
    [focus.identifier.id] NVARCHAR(100),
    [focus.identifier.extension] NVARCHAR(MAX),
    [focus.identifier.use] NVARCHAR(64),
    [focus.identifier.type] NVARCHAR(MAX),
    [focus.identifier.system] VARCHAR(256),
    [focus.identifier.value] NVARCHAR(4000),
    [focus.identifier.period] NVARCHAR(MAX),
    [focus.identifier.assigner] NVARCHAR(MAX),
    [focus.display] NVARCHAR(4000),
    [for.id] NVARCHAR(100),
    [for.extension] NVARCHAR(MAX),
    [for.reference] NVARCHAR(4000),
    [for.type] VARCHAR(256),
    [for.identifier.id] NVARCHAR(100),
    [for.identifier.extension] NVARCHAR(MAX),
    [for.identifier.use] NVARCHAR(64),
    [for.identifier.type] NVARCHAR(MAX),
    [for.identifier.system] VARCHAR(256),
    [for.identifier.value] NVARCHAR(4000),
    [for.identifier.period] NVARCHAR(MAX),
    [for.identifier.assigner] NVARCHAR(MAX),
    [for.display] NVARCHAR(4000),
    [encounter.id] NVARCHAR(100),
    [encounter.extension] NVARCHAR(MAX),
    [encounter.reference] NVARCHAR(4000),
    [encounter.type] VARCHAR(256),
    [encounter.identifier.id] NVARCHAR(100),
    [encounter.identifier.extension] NVARCHAR(MAX),
    [encounter.identifier.use] NVARCHAR(64),
    [encounter.identifier.type] NVARCHAR(MAX),
    [encounter.identifier.system] VARCHAR(256),
    [encounter.identifier.value] NVARCHAR(4000),
    [encounter.identifier.period] NVARCHAR(MAX),
    [encounter.identifier.assigner] NVARCHAR(MAX),
    [encounter.display] NVARCHAR(4000),
    [executionPeriod.id] NVARCHAR(100),
    [executionPeriod.extension] NVARCHAR(MAX),
    [executionPeriod.start] VARCHAR(64),
    [executionPeriod.end] VARCHAR(64),
    [authoredOn] VARCHAR(64),
    [lastModified] VARCHAR(64),
    [requester.id] NVARCHAR(100),
    [requester.extension] NVARCHAR(MAX),
    [requester.reference] NVARCHAR(4000),
    [requester.type] VARCHAR(256),
    [requester.identifier.id] NVARCHAR(100),
    [requester.identifier.extension] NVARCHAR(MAX),
    [requester.identifier.use] NVARCHAR(64),
    [requester.identifier.type] NVARCHAR(MAX),
    [requester.identifier.system] VARCHAR(256),
    [requester.identifier.value] NVARCHAR(4000),
    [requester.identifier.period] NVARCHAR(MAX),
    [requester.identifier.assigner] NVARCHAR(MAX),
    [requester.display] NVARCHAR(4000),
    [performerType] VARCHAR(MAX),
    [owner.id] NVARCHAR(100),
    [owner.extension] NVARCHAR(MAX),
    [owner.reference] NVARCHAR(4000),
    [owner.type] VARCHAR(256),
    [owner.identifier.id] NVARCHAR(100),
    [owner.identifier.extension] NVARCHAR(MAX),
    [owner.identifier.use] NVARCHAR(64),
    [owner.identifier.type] NVARCHAR(MAX),
    [owner.identifier.system] VARCHAR(256),
    [owner.identifier.value] NVARCHAR(4000),
    [owner.identifier.period] NVARCHAR(MAX),
    [owner.identifier.assigner] NVARCHAR(MAX),
    [owner.display] NVARCHAR(4000),
    [location.id] NVARCHAR(100),
    [location.extension] NVARCHAR(MAX),
    [location.reference] NVARCHAR(4000),
    [location.type] VARCHAR(256),
    [location.identifier.id] NVARCHAR(100),
    [location.identifier.extension] NVARCHAR(MAX),
    [location.identifier.use] NVARCHAR(64),
    [location.identifier.type] NVARCHAR(MAX),
    [location.identifier.system] VARCHAR(256),
    [location.identifier.value] NVARCHAR(4000),
    [location.identifier.period] NVARCHAR(MAX),
    [location.identifier.assigner] NVARCHAR(MAX),
    [location.display] NVARCHAR(4000),
    [reasonCode.id] NVARCHAR(100),
    [reasonCode.extension] NVARCHAR(MAX),
    [reasonCode.coding] VARCHAR(MAX),
    [reasonCode.text] NVARCHAR(4000),
    [reasonReference.id] NVARCHAR(100),
    [reasonReference.extension] NVARCHAR(MAX),
    [reasonReference.reference] NVARCHAR(4000),
    [reasonReference.type] VARCHAR(256),
    [reasonReference.identifier.id] NVARCHAR(100),
    [reasonReference.identifier.extension] NVARCHAR(MAX),
    [reasonReference.identifier.use] NVARCHAR(64),
    [reasonReference.identifier.type] NVARCHAR(MAX),
    [reasonReference.identifier.system] VARCHAR(256),
    [reasonReference.identifier.value] NVARCHAR(4000),
    [reasonReference.identifier.period] NVARCHAR(MAX),
    [reasonReference.identifier.assigner] NVARCHAR(MAX),
    [reasonReference.display] NVARCHAR(4000),
    [insurance] VARCHAR(MAX),
    [note] VARCHAR(MAX),
    [relevantHistory] VARCHAR(MAX),
    [restriction.id] NVARCHAR(100),
    [restriction.extension] NVARCHAR(MAX),
    [restriction.modifierExtension] NVARCHAR(MAX),
    [restriction.repetitions] bigint,
    [restriction.period.id] NVARCHAR(100),
    [restriction.period.extension] NVARCHAR(MAX),
    [restriction.period.start] VARCHAR(64),
    [restriction.period.end] VARCHAR(64),
    [restriction.recipient] VARCHAR(MAX),
    [input] VARCHAR(MAX),
    [output] VARCHAR(MAX),
) WITH (
    LOCATION='/Task/**',
    DATA_SOURCE = ParquetSource,
    FILE_FORMAT = ParquetFormat
);

GO

CREATE VIEW fhir.TaskIdentifier AS
SELECT
    [id],
    [identifier.JSON],
    [identifier.id],
    [identifier.extension],
    [identifier.use],
    [identifier.type.id],
    [identifier.type.extension],
    [identifier.type.coding],
    [identifier.type.text],
    [identifier.system],
    [identifier.value],
    [identifier.period.id],
    [identifier.period.extension],
    [identifier.period.start],
    [identifier.period.end],
    [identifier.assigner.id],
    [identifier.assigner.extension],
    [identifier.assigner.reference],
    [identifier.assigner.type],
    [identifier.assigner.identifier],
    [identifier.assigner.display]
FROM openrowset (
        BULK 'Task/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [identifier.JSON]  VARCHAR(MAX) '$.identifier'
    ) AS rowset
    CROSS APPLY openjson (rowset.[identifier.JSON]) with (
        [identifier.id]                NVARCHAR(100)       '$.id',
        [identifier.extension]         NVARCHAR(MAX)       '$.extension',
        [identifier.use]               NVARCHAR(64)        '$.use',
        [identifier.type.id]           NVARCHAR(100)       '$.type.id',
        [identifier.type.extension]    NVARCHAR(MAX)       '$.type.extension',
        [identifier.type.coding]       NVARCHAR(MAX)       '$.type.coding',
        [identifier.type.text]         NVARCHAR(4000)      '$.type.text',
        [identifier.system]            VARCHAR(256)        '$.system',
        [identifier.value]             NVARCHAR(4000)      '$.value',
        [identifier.period.id]         NVARCHAR(100)       '$.period.id',
        [identifier.period.extension]  NVARCHAR(MAX)       '$.period.extension',
        [identifier.period.start]      VARCHAR(64)         '$.period.start',
        [identifier.period.end]        VARCHAR(64)         '$.period.end',
        [identifier.assigner.id]       NVARCHAR(100)       '$.assigner.id',
        [identifier.assigner.extension] NVARCHAR(MAX)       '$.assigner.extension',
        [identifier.assigner.reference] NVARCHAR(4000)      '$.assigner.reference',
        [identifier.assigner.type]     VARCHAR(256)        '$.assigner.type',
        [identifier.assigner.identifier] NVARCHAR(MAX)       '$.assigner.identifier',
        [identifier.assigner.display]  NVARCHAR(4000)      '$.assigner.display'
    ) j

GO

CREATE VIEW fhir.TaskBasedOn AS
SELECT
    [id],
    [basedOn.JSON],
    [basedOn.id],
    [basedOn.extension],
    [basedOn.reference],
    [basedOn.type],
    [basedOn.identifier.id],
    [basedOn.identifier.extension],
    [basedOn.identifier.use],
    [basedOn.identifier.type],
    [basedOn.identifier.system],
    [basedOn.identifier.value],
    [basedOn.identifier.period],
    [basedOn.identifier.assigner],
    [basedOn.display]
FROM openrowset (
        BULK 'Task/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [basedOn.JSON]  VARCHAR(MAX) '$.basedOn'
    ) AS rowset
    CROSS APPLY openjson (rowset.[basedOn.JSON]) with (
        [basedOn.id]                   NVARCHAR(100)       '$.id',
        [basedOn.extension]            NVARCHAR(MAX)       '$.extension',
        [basedOn.reference]            NVARCHAR(4000)      '$.reference',
        [basedOn.type]                 VARCHAR(256)        '$.type',
        [basedOn.identifier.id]        NVARCHAR(100)       '$.identifier.id',
        [basedOn.identifier.extension] NVARCHAR(MAX)       '$.identifier.extension',
        [basedOn.identifier.use]       NVARCHAR(64)        '$.identifier.use',
        [basedOn.identifier.type]      NVARCHAR(MAX)       '$.identifier.type',
        [basedOn.identifier.system]    VARCHAR(256)        '$.identifier.system',
        [basedOn.identifier.value]     NVARCHAR(4000)      '$.identifier.value',
        [basedOn.identifier.period]    NVARCHAR(MAX)       '$.identifier.period',
        [basedOn.identifier.assigner]  NVARCHAR(MAX)       '$.identifier.assigner',
        [basedOn.display]              NVARCHAR(4000)      '$.display'
    ) j

GO

CREATE VIEW fhir.TaskPartOf AS
SELECT
    [id],
    [partOf.JSON],
    [partOf.id],
    [partOf.extension],
    [partOf.reference],
    [partOf.type],
    [partOf.identifier.id],
    [partOf.identifier.extension],
    [partOf.identifier.use],
    [partOf.identifier.type],
    [partOf.identifier.system],
    [partOf.identifier.value],
    [partOf.identifier.period],
    [partOf.identifier.assigner],
    [partOf.display]
FROM openrowset (
        BULK 'Task/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [partOf.JSON]  VARCHAR(MAX) '$.partOf'
    ) AS rowset
    CROSS APPLY openjson (rowset.[partOf.JSON]) with (
        [partOf.id]                    NVARCHAR(100)       '$.id',
        [partOf.extension]             NVARCHAR(MAX)       '$.extension',
        [partOf.reference]             NVARCHAR(4000)      '$.reference',
        [partOf.type]                  VARCHAR(256)        '$.type',
        [partOf.identifier.id]         NVARCHAR(100)       '$.identifier.id',
        [partOf.identifier.extension]  NVARCHAR(MAX)       '$.identifier.extension',
        [partOf.identifier.use]        NVARCHAR(64)        '$.identifier.use',
        [partOf.identifier.type]       NVARCHAR(MAX)       '$.identifier.type',
        [partOf.identifier.system]     VARCHAR(256)        '$.identifier.system',
        [partOf.identifier.value]      NVARCHAR(4000)      '$.identifier.value',
        [partOf.identifier.period]     NVARCHAR(MAX)       '$.identifier.period',
        [partOf.identifier.assigner]   NVARCHAR(MAX)       '$.identifier.assigner',
        [partOf.display]               NVARCHAR(4000)      '$.display'
    ) j

GO

CREATE VIEW fhir.TaskPerformerType AS
SELECT
    [id],
    [performerType.JSON],
    [performerType.id],
    [performerType.extension],
    [performerType.coding],
    [performerType.text]
FROM openrowset (
        BULK 'Task/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [performerType.JSON]  VARCHAR(MAX) '$.performerType'
    ) AS rowset
    CROSS APPLY openjson (rowset.[performerType.JSON]) with (
        [performerType.id]             NVARCHAR(100)       '$.id',
        [performerType.extension]      NVARCHAR(MAX)       '$.extension',
        [performerType.coding]         NVARCHAR(MAX)       '$.coding' AS JSON,
        [performerType.text]           NVARCHAR(4000)      '$.text'
    ) j

GO

CREATE VIEW fhir.TaskInsurance AS
SELECT
    [id],
    [insurance.JSON],
    [insurance.id],
    [insurance.extension],
    [insurance.reference],
    [insurance.type],
    [insurance.identifier.id],
    [insurance.identifier.extension],
    [insurance.identifier.use],
    [insurance.identifier.type],
    [insurance.identifier.system],
    [insurance.identifier.value],
    [insurance.identifier.period],
    [insurance.identifier.assigner],
    [insurance.display]
FROM openrowset (
        BULK 'Task/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [insurance.JSON]  VARCHAR(MAX) '$.insurance'
    ) AS rowset
    CROSS APPLY openjson (rowset.[insurance.JSON]) with (
        [insurance.id]                 NVARCHAR(100)       '$.id',
        [insurance.extension]          NVARCHAR(MAX)       '$.extension',
        [insurance.reference]          NVARCHAR(4000)      '$.reference',
        [insurance.type]               VARCHAR(256)        '$.type',
        [insurance.identifier.id]      NVARCHAR(100)       '$.identifier.id',
        [insurance.identifier.extension] NVARCHAR(MAX)       '$.identifier.extension',
        [insurance.identifier.use]     NVARCHAR(64)        '$.identifier.use',
        [insurance.identifier.type]    NVARCHAR(MAX)       '$.identifier.type',
        [insurance.identifier.system]  VARCHAR(256)        '$.identifier.system',
        [insurance.identifier.value]   NVARCHAR(4000)      '$.identifier.value',
        [insurance.identifier.period]  NVARCHAR(MAX)       '$.identifier.period',
        [insurance.identifier.assigner] NVARCHAR(MAX)       '$.identifier.assigner',
        [insurance.display]            NVARCHAR(4000)      '$.display'
    ) j

GO

CREATE VIEW fhir.TaskNote AS
SELECT
    [id],
    [note.JSON],
    [note.id],
    [note.extension],
    [note.time],
    [note.text],
    [note.author.reference.id],
    [note.author.reference.extension],
    [note.author.reference.reference],
    [note.author.reference.type],
    [note.author.reference.identifier],
    [note.author.reference.display],
    [note.author.string]
FROM openrowset (
        BULK 'Task/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [note.JSON]  VARCHAR(MAX) '$.note'
    ) AS rowset
    CROSS APPLY openjson (rowset.[note.JSON]) with (
        [note.id]                      NVARCHAR(100)       '$.id',
        [note.extension]               NVARCHAR(MAX)       '$.extension',
        [note.time]                    VARCHAR(64)         '$.time',
        [note.text]                    NVARCHAR(MAX)       '$.text',
        [note.author.reference.id]     NVARCHAR(100)       '$.author.reference.id',
        [note.author.reference.extension] NVARCHAR(MAX)       '$.author.reference.extension',
        [note.author.reference.reference] NVARCHAR(4000)      '$.author.reference.reference',
        [note.author.reference.type]   VARCHAR(256)        '$.author.reference.type',
        [note.author.reference.identifier] NVARCHAR(MAX)       '$.author.reference.identifier',
        [note.author.reference.display] NVARCHAR(4000)      '$.author.reference.display',
        [note.author.string]           NVARCHAR(4000)      '$.author.string'
    ) j

GO

CREATE VIEW fhir.TaskRelevantHistory AS
SELECT
    [id],
    [relevantHistory.JSON],
    [relevantHistory.id],
    [relevantHistory.extension],
    [relevantHistory.reference],
    [relevantHistory.type],
    [relevantHistory.identifier.id],
    [relevantHistory.identifier.extension],
    [relevantHistory.identifier.use],
    [relevantHistory.identifier.type],
    [relevantHistory.identifier.system],
    [relevantHistory.identifier.value],
    [relevantHistory.identifier.period],
    [relevantHistory.identifier.assigner],
    [relevantHistory.display]
FROM openrowset (
        BULK 'Task/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [relevantHistory.JSON]  VARCHAR(MAX) '$.relevantHistory'
    ) AS rowset
    CROSS APPLY openjson (rowset.[relevantHistory.JSON]) with (
        [relevantHistory.id]           NVARCHAR(100)       '$.id',
        [relevantHistory.extension]    NVARCHAR(MAX)       '$.extension',
        [relevantHistory.reference]    NVARCHAR(4000)      '$.reference',
        [relevantHistory.type]         VARCHAR(256)        '$.type',
        [relevantHistory.identifier.id] NVARCHAR(100)       '$.identifier.id',
        [relevantHistory.identifier.extension] NVARCHAR(MAX)       '$.identifier.extension',
        [relevantHistory.identifier.use] NVARCHAR(64)        '$.identifier.use',
        [relevantHistory.identifier.type] NVARCHAR(MAX)       '$.identifier.type',
        [relevantHistory.identifier.system] VARCHAR(256)        '$.identifier.system',
        [relevantHistory.identifier.value] NVARCHAR(4000)      '$.identifier.value',
        [relevantHistory.identifier.period] NVARCHAR(MAX)       '$.identifier.period',
        [relevantHistory.identifier.assigner] NVARCHAR(MAX)       '$.identifier.assigner',
        [relevantHistory.display]      NVARCHAR(4000)      '$.display'
    ) j

GO

CREATE VIEW fhir.TaskInput AS
SELECT
    [id],
    [input.JSON],
    [input.id],
    [input.extension],
    [input.modifierExtension],
    [input.type.id],
    [input.type.extension],
    [input.type.coding],
    [input.type.text],
    [input.value.base64Binary],
    [input.value.boolean],
    [input.value.canonical],
    [input.value.code],
    [input.value.date],
    [input.value.dateTime],
    [input.value.decimal],
    [input.value.id],
    [input.value.instant],
    [input.value.integer],
    [input.value.markdown],
    [input.value.oid],
    [input.value.positiveInt],
    [input.value.string],
    [input.value.time],
    [input.value.unsignedInt],
    [input.value.uri],
    [input.value.url],
    [input.value.uuid],
    [input.value.address.id],
    [input.value.address.extension],
    [input.value.address.use],
    [input.value.address.type],
    [input.value.address.text],
    [input.value.address.line],
    [input.value.address.city],
    [input.value.address.district],
    [input.value.address.state],
    [input.value.address.postalCode],
    [input.value.address.country],
    [input.value.address.period],
    [input.value.age.id],
    [input.value.age.extension],
    [input.value.age.value],
    [input.value.age.comparator],
    [input.value.age.unit],
    [input.value.age.system],
    [input.value.age.code],
    [input.value.annotation.id],
    [input.value.annotation.extension],
    [input.value.annotation.time],
    [input.value.annotation.text],
    [input.value.annotation.author.reference],
    [input.value.annotation.author.string],
    [input.value.attachment.id],
    [input.value.attachment.extension],
    [input.value.attachment.contentType],
    [input.value.attachment.language],
    [input.value.attachment.data],
    [input.value.attachment.url],
    [input.value.attachment.size],
    [input.value.attachment.hash],
    [input.value.attachment.title],
    [input.value.attachment.creation],
    [input.value.codeableConcept.id],
    [input.value.codeableConcept.extension],
    [input.value.codeableConcept.coding],
    [input.value.codeableConcept.text],
    [input.value.coding.id],
    [input.value.coding.extension],
    [input.value.coding.system],
    [input.value.coding.version],
    [input.value.coding.code],
    [input.value.coding.display],
    [input.value.coding.userSelected],
    [input.value.contactPoint.id],
    [input.value.contactPoint.extension],
    [input.value.contactPoint.system],
    [input.value.contactPoint.value],
    [input.value.contactPoint.use],
    [input.value.contactPoint.rank],
    [input.value.contactPoint.period],
    [input.value.count.id],
    [input.value.count.extension],
    [input.value.count.value],
    [input.value.count.comparator],
    [input.value.count.unit],
    [input.value.count.system],
    [input.value.count.code],
    [input.value.distance.id],
    [input.value.distance.extension],
    [input.value.distance.value],
    [input.value.distance.comparator],
    [input.value.distance.unit],
    [input.value.distance.system],
    [input.value.distance.code],
    [input.value.duration.id],
    [input.value.duration.extension],
    [input.value.duration.value],
    [input.value.duration.comparator],
    [input.value.duration.unit],
    [input.value.duration.system],
    [input.value.duration.code],
    [input.value.humanName.id],
    [input.value.humanName.extension],
    [input.value.humanName.use],
    [input.value.humanName.text],
    [input.value.humanName.family],
    [input.value.humanName.given],
    [input.value.humanName.prefix],
    [input.value.humanName.suffix],
    [input.value.humanName.period],
    [input.value.identifier.id],
    [input.value.identifier.extension],
    [input.value.identifier.use],
    [input.value.identifier.type],
    [input.value.identifier.system],
    [input.value.identifier.value],
    [input.value.identifier.period],
    [input.value.identifier.assigner],
    [input.value.money.id],
    [input.value.money.extension],
    [input.value.money.value],
    [input.value.money.currency],
    [input.value.period.id],
    [input.value.period.extension],
    [input.value.period.start],
    [input.value.period.end],
    [input.value.quantity.id],
    [input.value.quantity.extension],
    [input.value.quantity.value],
    [input.value.quantity.comparator],
    [input.value.quantity.unit],
    [input.value.quantity.system],
    [input.value.quantity.code],
    [input.value.range.id],
    [input.value.range.extension],
    [input.value.range.low],
    [input.value.range.high],
    [input.value.ratio.id],
    [input.value.ratio.extension],
    [input.value.ratio.numerator],
    [input.value.ratio.denominator],
    [input.value.reference.id],
    [input.value.reference.extension],
    [input.value.reference.reference],
    [input.value.reference.type],
    [input.value.reference.identifier],
    [input.value.reference.display],
    [input.value.sampledData.id],
    [input.value.sampledData.extension],
    [input.value.sampledData.origin],
    [input.value.sampledData.period],
    [input.value.sampledData.factor],
    [input.value.sampledData.lowerLimit],
    [input.value.sampledData.upperLimit],
    [input.value.sampledData.dimensions],
    [input.value.sampledData.data],
    [input.value.signature.id],
    [input.value.signature.extension],
    [input.value.signature.type],
    [input.value.signature.when],
    [input.value.signature.who],
    [input.value.signature.onBehalfOf],
    [input.value.signature.targetFormat],
    [input.value.signature.sigFormat],
    [input.value.signature.data],
    [input.value.timing.id],
    [input.value.timing.extension],
    [input.value.timing.modifierExtension],
    [input.value.timing.event],
    [input.value.timing.repeat],
    [input.value.timing.code],
    [input.value.contactDetail.id],
    [input.value.contactDetail.extension],
    [input.value.contactDetail.name],
    [input.value.contactDetail.telecom],
    [input.value.contributor.id],
    [input.value.contributor.extension],
    [input.value.contributor.type],
    [input.value.contributor.name],
    [input.value.contributor.contact],
    [input.value.dataRequirement.id],
    [input.value.dataRequirement.extension],
    [input.value.dataRequirement.type],
    [input.value.dataRequirement.profile],
    [input.value.dataRequirement.mustSupport],
    [input.value.dataRequirement.codeFilter],
    [input.value.dataRequirement.dateFilter],
    [input.value.dataRequirement.limit],
    [input.value.dataRequirement.sort],
    [input.value.dataRequirement.subject.codeableConcept],
    [input.value.dataRequirement.subject.reference],
    [input.value.expression.id],
    [input.value.expression.extension],
    [input.value.expression.description],
    [input.value.expression.name],
    [input.value.expression.language],
    [input.value.expression.expression],
    [input.value.expression.reference],
    [input.value.parameterDefinition.id],
    [input.value.parameterDefinition.extension],
    [input.value.parameterDefinition.name],
    [input.value.parameterDefinition.use],
    [input.value.parameterDefinition.min],
    [input.value.parameterDefinition.max],
    [input.value.parameterDefinition.documentation],
    [input.value.parameterDefinition.type],
    [input.value.parameterDefinition.profile],
    [input.value.relatedArtifact.id],
    [input.value.relatedArtifact.extension],
    [input.value.relatedArtifact.type],
    [input.value.relatedArtifact.label],
    [input.value.relatedArtifact.display],
    [input.value.relatedArtifact.citation],
    [input.value.relatedArtifact.url],
    [input.value.relatedArtifact.document],
    [input.value.relatedArtifact.resource],
    [input.value.triggerDefinition.id],
    [input.value.triggerDefinition.extension],
    [input.value.triggerDefinition.type],
    [input.value.triggerDefinition.name],
    [input.value.triggerDefinition.data],
    [input.value.triggerDefinition.condition],
    [input.value.triggerDefinition.timing.timing],
    [input.value.triggerDefinition.timing.reference],
    [input.value.triggerDefinition.timing.date],
    [input.value.triggerDefinition.timing.dateTime],
    [input.value.usageContext.id],
    [input.value.usageContext.extension],
    [input.value.usageContext.code],
    [input.value.usageContext.value.codeableConcept],
    [input.value.usageContext.value.quantity],
    [input.value.usageContext.value.range],
    [input.value.usageContext.value.reference],
    [input.value.dosage.id],
    [input.value.dosage.extension],
    [input.value.dosage.modifierExtension],
    [input.value.dosage.sequence],
    [input.value.dosage.text],
    [input.value.dosage.additionalInstruction],
    [input.value.dosage.patientInstruction],
    [input.value.dosage.timing],
    [input.value.dosage.site],
    [input.value.dosage.route],
    [input.value.dosage.method],
    [input.value.dosage.doseAndRate],
    [input.value.dosage.maxDosePerPeriod],
    [input.value.dosage.maxDosePerAdministration],
    [input.value.dosage.maxDosePerLifetime],
    [input.value.dosage.asNeeded.boolean],
    [input.value.dosage.asNeeded.codeableConcept],
    [input.value.meta.id],
    [input.value.meta.extension],
    [input.value.meta.versionId],
    [input.value.meta.lastUpdated],
    [input.value.meta.source],
    [input.value.meta.profile],
    [input.value.meta.security],
    [input.value.meta.tag]
FROM openrowset (
        BULK 'Task/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [input.JSON]  VARCHAR(MAX) '$.input'
    ) AS rowset
    CROSS APPLY openjson (rowset.[input.JSON]) with (
        [input.id]                     NVARCHAR(100)       '$.id',
        [input.extension]              NVARCHAR(MAX)       '$.extension',
        [input.modifierExtension]      NVARCHAR(MAX)       '$.modifierExtension',
        [input.type.id]                NVARCHAR(100)       '$.type.id',
        [input.type.extension]         NVARCHAR(MAX)       '$.type.extension',
        [input.type.coding]            NVARCHAR(MAX)       '$.type.coding',
        [input.type.text]              NVARCHAR(4000)      '$.type.text',
        [input.value.base64Binary]     NVARCHAR(MAX)       '$.value.base64Binary',
        [input.value.boolean]          bit                 '$.value.boolean',
        [input.value.canonical]        VARCHAR(256)        '$.value.canonical',
        [input.value.code]             NVARCHAR(4000)      '$.value.code',
        [input.value.date]             VARCHAR(64)         '$.value.date',
        [input.value.dateTime]         VARCHAR(64)         '$.value.dateTime',
        [input.value.decimal]          float               '$.value.decimal',
        [input.value.id]               VARCHAR(64)         '$.value.id',
        [input.value.instant]          VARCHAR(64)         '$.value.instant',
        [input.value.integer]          bigint              '$.value.integer',
        [input.value.markdown]         NVARCHAR(MAX)       '$.value.markdown',
        [input.value.oid]              VARCHAR(64)         '$.value.oid',
        [input.value.positiveInt]      bigint              '$.value.positiveInt',
        [input.value.string]           NVARCHAR(4000)      '$.value.string',
        [input.value.time]             NVARCHAR(MAX)       '$.value.time',
        [input.value.unsignedInt]      bigint              '$.value.unsignedInt',
        [input.value.uri]              VARCHAR(256)        '$.value.uri',
        [input.value.url]              VARCHAR(256)        '$.value.url',
        [input.value.uuid]             NVARCHAR(MAX)       '$.value.uuid',
        [input.value.address.id]       NVARCHAR(100)       '$.value.address.id',
        [input.value.address.extension] NVARCHAR(MAX)       '$.value.address.extension',
        [input.value.address.use]      NVARCHAR(64)        '$.value.address.use',
        [input.value.address.type]     NVARCHAR(64)        '$.value.address.type',
        [input.value.address.text]     NVARCHAR(4000)      '$.value.address.text',
        [input.value.address.line]     NVARCHAR(MAX)       '$.value.address.line',
        [input.value.address.city]     NVARCHAR(500)       '$.value.address.city',
        [input.value.address.district] NVARCHAR(500)       '$.value.address.district',
        [input.value.address.state]    NVARCHAR(500)       '$.value.address.state',
        [input.value.address.postalCode] NVARCHAR(100)       '$.value.address.postalCode',
        [input.value.address.country]  NVARCHAR(500)       '$.value.address.country',
        [input.value.address.period]   NVARCHAR(MAX)       '$.value.address.period',
        [input.value.age.id]           NVARCHAR(100)       '$.value.age.id',
        [input.value.age.extension]    NVARCHAR(MAX)       '$.value.age.extension',
        [input.value.age.value]        float               '$.value.age.value',
        [input.value.age.comparator]   NVARCHAR(64)        '$.value.age.comparator',
        [input.value.age.unit]         NVARCHAR(100)       '$.value.age.unit',
        [input.value.age.system]       VARCHAR(256)        '$.value.age.system',
        [input.value.age.code]         NVARCHAR(4000)      '$.value.age.code',
        [input.value.annotation.id]    NVARCHAR(100)       '$.value.annotation.id',
        [input.value.annotation.extension] NVARCHAR(MAX)       '$.value.annotation.extension',
        [input.value.annotation.time]  VARCHAR(64)         '$.value.annotation.time',
        [input.value.annotation.text]  NVARCHAR(MAX)       '$.value.annotation.text',
        [input.value.annotation.author.reference] NVARCHAR(MAX)       '$.value.annotation.author.reference',
        [input.value.annotation.author.string] NVARCHAR(4000)      '$.value.annotation.author.string',
        [input.value.attachment.id]    NVARCHAR(100)       '$.value.attachment.id',
        [input.value.attachment.extension] NVARCHAR(MAX)       '$.value.attachment.extension',
        [input.value.attachment.contentType] NVARCHAR(100)       '$.value.attachment.contentType',
        [input.value.attachment.language] NVARCHAR(100)       '$.value.attachment.language',
        [input.value.attachment.data]  NVARCHAR(MAX)       '$.value.attachment.data',
        [input.value.attachment.url]   VARCHAR(256)        '$.value.attachment.url',
        [input.value.attachment.size]  bigint              '$.value.attachment.size',
        [input.value.attachment.hash]  NVARCHAR(MAX)       '$.value.attachment.hash',
        [input.value.attachment.title] NVARCHAR(4000)      '$.value.attachment.title',
        [input.value.attachment.creation] VARCHAR(64)         '$.value.attachment.creation',
        [input.value.codeableConcept.id] NVARCHAR(100)       '$.value.codeableConcept.id',
        [input.value.codeableConcept.extension] NVARCHAR(MAX)       '$.value.codeableConcept.extension',
        [input.value.codeableConcept.coding] NVARCHAR(MAX)       '$.value.codeableConcept.coding',
        [input.value.codeableConcept.text] NVARCHAR(4000)      '$.value.codeableConcept.text',
        [input.value.coding.id]        NVARCHAR(100)       '$.value.coding.id',
        [input.value.coding.extension] NVARCHAR(MAX)       '$.value.coding.extension',
        [input.value.coding.system]    VARCHAR(256)        '$.value.coding.system',
        [input.value.coding.version]   NVARCHAR(100)       '$.value.coding.version',
        [input.value.coding.code]      NVARCHAR(4000)      '$.value.coding.code',
        [input.value.coding.display]   NVARCHAR(4000)      '$.value.coding.display',
        [input.value.coding.userSelected] bit                 '$.value.coding.userSelected',
        [input.value.contactPoint.id]  NVARCHAR(100)       '$.value.contactPoint.id',
        [input.value.contactPoint.extension] NVARCHAR(MAX)       '$.value.contactPoint.extension',
        [input.value.contactPoint.system] NVARCHAR(64)        '$.value.contactPoint.system',
        [input.value.contactPoint.value] NVARCHAR(4000)      '$.value.contactPoint.value',
        [input.value.contactPoint.use] NVARCHAR(64)        '$.value.contactPoint.use',
        [input.value.contactPoint.rank] bigint              '$.value.contactPoint.rank',
        [input.value.contactPoint.period] NVARCHAR(MAX)       '$.value.contactPoint.period',
        [input.value.count.id]         NVARCHAR(100)       '$.value.count.id',
        [input.value.count.extension]  NVARCHAR(MAX)       '$.value.count.extension',
        [input.value.count.value]      float               '$.value.count.value',
        [input.value.count.comparator] NVARCHAR(64)        '$.value.count.comparator',
        [input.value.count.unit]       NVARCHAR(100)       '$.value.count.unit',
        [input.value.count.system]     VARCHAR(256)        '$.value.count.system',
        [input.value.count.code]       NVARCHAR(4000)      '$.value.count.code',
        [input.value.distance.id]      NVARCHAR(100)       '$.value.distance.id',
        [input.value.distance.extension] NVARCHAR(MAX)       '$.value.distance.extension',
        [input.value.distance.value]   float               '$.value.distance.value',
        [input.value.distance.comparator] NVARCHAR(64)        '$.value.distance.comparator',
        [input.value.distance.unit]    NVARCHAR(100)       '$.value.distance.unit',
        [input.value.distance.system]  VARCHAR(256)        '$.value.distance.system',
        [input.value.distance.code]    NVARCHAR(4000)      '$.value.distance.code',
        [input.value.duration.id]      NVARCHAR(100)       '$.value.duration.id',
        [input.value.duration.extension] NVARCHAR(MAX)       '$.value.duration.extension',
        [input.value.duration.value]   float               '$.value.duration.value',
        [input.value.duration.comparator] NVARCHAR(64)        '$.value.duration.comparator',
        [input.value.duration.unit]    NVARCHAR(100)       '$.value.duration.unit',
        [input.value.duration.system]  VARCHAR(256)        '$.value.duration.system',
        [input.value.duration.code]    NVARCHAR(4000)      '$.value.duration.code',
        [input.value.humanName.id]     NVARCHAR(100)       '$.value.humanName.id',
        [input.value.humanName.extension] NVARCHAR(MAX)       '$.value.humanName.extension',
        [input.value.humanName.use]    NVARCHAR(64)        '$.value.humanName.use',
        [input.value.humanName.text]   NVARCHAR(4000)      '$.value.humanName.text',
        [input.value.humanName.family] NVARCHAR(500)       '$.value.humanName.family',
        [input.value.humanName.given]  NVARCHAR(MAX)       '$.value.humanName.given',
        [input.value.humanName.prefix] NVARCHAR(MAX)       '$.value.humanName.prefix',
        [input.value.humanName.suffix] NVARCHAR(MAX)       '$.value.humanName.suffix',
        [input.value.humanName.period] NVARCHAR(MAX)       '$.value.humanName.period',
        [input.value.identifier.id]    NVARCHAR(100)       '$.value.identifier.id',
        [input.value.identifier.extension] NVARCHAR(MAX)       '$.value.identifier.extension',
        [input.value.identifier.use]   NVARCHAR(64)        '$.value.identifier.use',
        [input.value.identifier.type]  NVARCHAR(MAX)       '$.value.identifier.type',
        [input.value.identifier.system] VARCHAR(256)        '$.value.identifier.system',
        [input.value.identifier.value] NVARCHAR(4000)      '$.value.identifier.value',
        [input.value.identifier.period] NVARCHAR(MAX)       '$.value.identifier.period',
        [input.value.identifier.assigner] NVARCHAR(MAX)       '$.value.identifier.assigner',
        [input.value.money.id]         NVARCHAR(100)       '$.value.money.id',
        [input.value.money.extension]  NVARCHAR(MAX)       '$.value.money.extension',
        [input.value.money.value]      float               '$.value.money.value',
        [input.value.money.currency]   NVARCHAR(100)       '$.value.money.currency',
        [input.value.period.id]        NVARCHAR(100)       '$.value.period.id',
        [input.value.period.extension] NVARCHAR(MAX)       '$.value.period.extension',
        [input.value.period.start]     VARCHAR(64)         '$.value.period.start',
        [input.value.period.end]       VARCHAR(64)         '$.value.period.end',
        [input.value.quantity.id]      NVARCHAR(100)       '$.value.quantity.id',
        [input.value.quantity.extension] NVARCHAR(MAX)       '$.value.quantity.extension',
        [input.value.quantity.value]   float               '$.value.quantity.value',
        [input.value.quantity.comparator] NVARCHAR(64)        '$.value.quantity.comparator',
        [input.value.quantity.unit]    NVARCHAR(100)       '$.value.quantity.unit',
        [input.value.quantity.system]  VARCHAR(256)        '$.value.quantity.system',
        [input.value.quantity.code]    NVARCHAR(4000)      '$.value.quantity.code',
        [input.value.range.id]         NVARCHAR(100)       '$.value.range.id',
        [input.value.range.extension]  NVARCHAR(MAX)       '$.value.range.extension',
        [input.value.range.low]        NVARCHAR(MAX)       '$.value.range.low',
        [input.value.range.high]       NVARCHAR(MAX)       '$.value.range.high',
        [input.value.ratio.id]         NVARCHAR(100)       '$.value.ratio.id',
        [input.value.ratio.extension]  NVARCHAR(MAX)       '$.value.ratio.extension',
        [input.value.ratio.numerator]  NVARCHAR(MAX)       '$.value.ratio.numerator',
        [input.value.ratio.denominator] NVARCHAR(MAX)       '$.value.ratio.denominator',
        [input.value.reference.id]     NVARCHAR(100)       '$.value.reference.id',
        [input.value.reference.extension] NVARCHAR(MAX)       '$.value.reference.extension',
        [input.value.reference.reference] NVARCHAR(4000)      '$.value.reference.reference',
        [input.value.reference.type]   VARCHAR(256)        '$.value.reference.type',
        [input.value.reference.identifier] NVARCHAR(MAX)       '$.value.reference.identifier',
        [input.value.reference.display] NVARCHAR(4000)      '$.value.reference.display',
        [input.value.sampledData.id]   NVARCHAR(100)       '$.value.sampledData.id',
        [input.value.sampledData.extension] NVARCHAR(MAX)       '$.value.sampledData.extension',
        [input.value.sampledData.origin] NVARCHAR(MAX)       '$.value.sampledData.origin',
        [input.value.sampledData.period] float               '$.value.sampledData.period',
        [input.value.sampledData.factor] float               '$.value.sampledData.factor',
        [input.value.sampledData.lowerLimit] float               '$.value.sampledData.lowerLimit',
        [input.value.sampledData.upperLimit] float               '$.value.sampledData.upperLimit',
        [input.value.sampledData.dimensions] bigint              '$.value.sampledData.dimensions',
        [input.value.sampledData.data] NVARCHAR(4000)      '$.value.sampledData.data',
        [input.value.signature.id]     NVARCHAR(100)       '$.value.signature.id',
        [input.value.signature.extension] NVARCHAR(MAX)       '$.value.signature.extension',
        [input.value.signature.type]   NVARCHAR(MAX)       '$.value.signature.type',
        [input.value.signature.when]   VARCHAR(64)         '$.value.signature.when',
        [input.value.signature.who]    NVARCHAR(MAX)       '$.value.signature.who',
        [input.value.signature.onBehalfOf] NVARCHAR(MAX)       '$.value.signature.onBehalfOf',
        [input.value.signature.targetFormat] NVARCHAR(100)       '$.value.signature.targetFormat',
        [input.value.signature.sigFormat] NVARCHAR(100)       '$.value.signature.sigFormat',
        [input.value.signature.data]   NVARCHAR(MAX)       '$.value.signature.data',
        [input.value.timing.id]        NVARCHAR(100)       '$.value.timing.id',
        [input.value.timing.extension] NVARCHAR(MAX)       '$.value.timing.extension',
        [input.value.timing.modifierExtension] NVARCHAR(MAX)       '$.value.timing.modifierExtension',
        [input.value.timing.event]     NVARCHAR(MAX)       '$.value.timing.event',
        [input.value.timing.repeat]    NVARCHAR(MAX)       '$.value.timing.repeat',
        [input.value.timing.code]      NVARCHAR(MAX)       '$.value.timing.code',
        [input.value.contactDetail.id] NVARCHAR(100)       '$.value.contactDetail.id',
        [input.value.contactDetail.extension] NVARCHAR(MAX)       '$.value.contactDetail.extension',
        [input.value.contactDetail.name] NVARCHAR(500)       '$.value.contactDetail.name',
        [input.value.contactDetail.telecom] NVARCHAR(MAX)       '$.value.contactDetail.telecom',
        [input.value.contributor.id]   NVARCHAR(100)       '$.value.contributor.id',
        [input.value.contributor.extension] NVARCHAR(MAX)       '$.value.contributor.extension',
        [input.value.contributor.type] NVARCHAR(64)        '$.value.contributor.type',
        [input.value.contributor.name] NVARCHAR(500)       '$.value.contributor.name',
        [input.value.contributor.contact] NVARCHAR(MAX)       '$.value.contributor.contact',
        [input.value.dataRequirement.id] NVARCHAR(100)       '$.value.dataRequirement.id',
        [input.value.dataRequirement.extension] NVARCHAR(MAX)       '$.value.dataRequirement.extension',
        [input.value.dataRequirement.type] NVARCHAR(100)       '$.value.dataRequirement.type',
        [input.value.dataRequirement.profile] NVARCHAR(MAX)       '$.value.dataRequirement.profile',
        [input.value.dataRequirement.mustSupport] NVARCHAR(MAX)       '$.value.dataRequirement.mustSupport',
        [input.value.dataRequirement.codeFilter] NVARCHAR(MAX)       '$.value.dataRequirement.codeFilter',
        [input.value.dataRequirement.dateFilter] NVARCHAR(MAX)       '$.value.dataRequirement.dateFilter',
        [input.value.dataRequirement.limit] bigint              '$.value.dataRequirement.limit',
        [input.value.dataRequirement.sort] NVARCHAR(MAX)       '$.value.dataRequirement.sort',
        [input.value.dataRequirement.subject.codeableConcept] NVARCHAR(MAX)       '$.value.dataRequirement.subject.codeableConcept',
        [input.value.dataRequirement.subject.reference] NVARCHAR(MAX)       '$.value.dataRequirement.subject.reference',
        [input.value.expression.id]    NVARCHAR(100)       '$.value.expression.id',
        [input.value.expression.extension] NVARCHAR(MAX)       '$.value.expression.extension',
        [input.value.expression.description] NVARCHAR(4000)      '$.value.expression.description',
        [input.value.expression.name]  VARCHAR(64)         '$.value.expression.name',
        [input.value.expression.language] NVARCHAR(64)        '$.value.expression.language',
        [input.value.expression.expression] NVARCHAR(4000)      '$.value.expression.expression',
        [input.value.expression.reference] VARCHAR(256)        '$.value.expression.reference',
        [input.value.parameterDefinition.id] NVARCHAR(100)       '$.value.parameterDefinition.id',
        [input.value.parameterDefinition.extension] NVARCHAR(MAX)       '$.value.parameterDefinition.extension',
        [input.value.parameterDefinition.name] NVARCHAR(500)       '$.value.parameterDefinition.name',
        [input.value.parameterDefinition.use] NVARCHAR(100)       '$.value.parameterDefinition.use',
        [input.value.parameterDefinition.min] bigint              '$.value.parameterDefinition.min',
        [input.value.parameterDefinition.max] NVARCHAR(100)       '$.value.parameterDefinition.max',
        [input.value.parameterDefinition.documentation] NVARCHAR(4000)      '$.value.parameterDefinition.documentation',
        [input.value.parameterDefinition.type] NVARCHAR(100)       '$.value.parameterDefinition.type',
        [input.value.parameterDefinition.profile] VARCHAR(256)        '$.value.parameterDefinition.profile',
        [input.value.relatedArtifact.id] NVARCHAR(100)       '$.value.relatedArtifact.id',
        [input.value.relatedArtifact.extension] NVARCHAR(MAX)       '$.value.relatedArtifact.extension',
        [input.value.relatedArtifact.type] NVARCHAR(64)        '$.value.relatedArtifact.type',
        [input.value.relatedArtifact.label] NVARCHAR(100)       '$.value.relatedArtifact.label',
        [input.value.relatedArtifact.display] NVARCHAR(4000)      '$.value.relatedArtifact.display',
        [input.value.relatedArtifact.citation] NVARCHAR(MAX)       '$.value.relatedArtifact.citation',
        [input.value.relatedArtifact.url] VARCHAR(256)        '$.value.relatedArtifact.url',
        [input.value.relatedArtifact.document] NVARCHAR(MAX)       '$.value.relatedArtifact.document',
        [input.value.relatedArtifact.resource] VARCHAR(256)        '$.value.relatedArtifact.resource',
        [input.value.triggerDefinition.id] NVARCHAR(100)       '$.value.triggerDefinition.id',
        [input.value.triggerDefinition.extension] NVARCHAR(MAX)       '$.value.triggerDefinition.extension',
        [input.value.triggerDefinition.type] NVARCHAR(64)        '$.value.triggerDefinition.type',
        [input.value.triggerDefinition.name] NVARCHAR(500)       '$.value.triggerDefinition.name',
        [input.value.triggerDefinition.data] NVARCHAR(MAX)       '$.value.triggerDefinition.data',
        [input.value.triggerDefinition.condition] NVARCHAR(MAX)       '$.value.triggerDefinition.condition',
        [input.value.triggerDefinition.timing.timing] NVARCHAR(MAX)       '$.value.triggerDefinition.timing.timing',
        [input.value.triggerDefinition.timing.reference] NVARCHAR(MAX)       '$.value.triggerDefinition.timing.reference',
        [input.value.triggerDefinition.timing.date] VARCHAR(64)         '$.value.triggerDefinition.timing.date',
        [input.value.triggerDefinition.timing.dateTime] VARCHAR(64)         '$.value.triggerDefinition.timing.dateTime',
        [input.value.usageContext.id]  NVARCHAR(100)       '$.value.usageContext.id',
        [input.value.usageContext.extension] NVARCHAR(MAX)       '$.value.usageContext.extension',
        [input.value.usageContext.code] NVARCHAR(MAX)       '$.value.usageContext.code',
        [input.value.usageContext.value.codeableConcept] NVARCHAR(MAX)       '$.value.usageContext.value.codeableConcept',
        [input.value.usageContext.value.quantity] NVARCHAR(MAX)       '$.value.usageContext.value.quantity',
        [input.value.usageContext.value.range] NVARCHAR(MAX)       '$.value.usageContext.value.range',
        [input.value.usageContext.value.reference] NVARCHAR(MAX)       '$.value.usageContext.value.reference',
        [input.value.dosage.id]        NVARCHAR(100)       '$.value.dosage.id',
        [input.value.dosage.extension] NVARCHAR(MAX)       '$.value.dosage.extension',
        [input.value.dosage.modifierExtension] NVARCHAR(MAX)       '$.value.dosage.modifierExtension',
        [input.value.dosage.sequence]  bigint              '$.value.dosage.sequence',
        [input.value.dosage.text]      NVARCHAR(4000)      '$.value.dosage.text',
        [input.value.dosage.additionalInstruction] NVARCHAR(MAX)       '$.value.dosage.additionalInstruction',
        [input.value.dosage.patientInstruction] NVARCHAR(4000)      '$.value.dosage.patientInstruction',
        [input.value.dosage.timing]    NVARCHAR(MAX)       '$.value.dosage.timing',
        [input.value.dosage.site]      NVARCHAR(MAX)       '$.value.dosage.site',
        [input.value.dosage.route]     NVARCHAR(MAX)       '$.value.dosage.route',
        [input.value.dosage.method]    NVARCHAR(MAX)       '$.value.dosage.method',
        [input.value.dosage.doseAndRate] NVARCHAR(MAX)       '$.value.dosage.doseAndRate',
        [input.value.dosage.maxDosePerPeriod] NVARCHAR(MAX)       '$.value.dosage.maxDosePerPeriod',
        [input.value.dosage.maxDosePerAdministration] NVARCHAR(MAX)       '$.value.dosage.maxDosePerAdministration',
        [input.value.dosage.maxDosePerLifetime] NVARCHAR(MAX)       '$.value.dosage.maxDosePerLifetime',
        [input.value.dosage.asNeeded.boolean] bit                 '$.value.dosage.asNeeded.boolean',
        [input.value.dosage.asNeeded.codeableConcept] NVARCHAR(MAX)       '$.value.dosage.asNeeded.codeableConcept',
        [input.value.meta.id]          NVARCHAR(100)       '$.value.meta.id',
        [input.value.meta.extension]   NVARCHAR(MAX)       '$.value.meta.extension',
        [input.value.meta.versionId]   VARCHAR(64)         '$.value.meta.versionId',
        [input.value.meta.lastUpdated] VARCHAR(64)         '$.value.meta.lastUpdated',
        [input.value.meta.source]      VARCHAR(256)        '$.value.meta.source',
        [input.value.meta.profile]     NVARCHAR(MAX)       '$.value.meta.profile',
        [input.value.meta.security]    NVARCHAR(MAX)       '$.value.meta.security',
        [input.value.meta.tag]         NVARCHAR(MAX)       '$.value.meta.tag'
    ) j

GO

CREATE VIEW fhir.TaskOutput AS
SELECT
    [id],
    [output.JSON],
    [output.id],
    [output.extension],
    [output.modifierExtension],
    [output.type.id],
    [output.type.extension],
    [output.type.coding],
    [output.type.text],
    [output.value.base64Binary],
    [output.value.boolean],
    [output.value.canonical],
    [output.value.code],
    [output.value.date],
    [output.value.dateTime],
    [output.value.decimal],
    [output.value.id],
    [output.value.instant],
    [output.value.integer],
    [output.value.markdown],
    [output.value.oid],
    [output.value.positiveInt],
    [output.value.string],
    [output.value.time],
    [output.value.unsignedInt],
    [output.value.uri],
    [output.value.url],
    [output.value.uuid],
    [output.value.address.id],
    [output.value.address.extension],
    [output.value.address.use],
    [output.value.address.type],
    [output.value.address.text],
    [output.value.address.line],
    [output.value.address.city],
    [output.value.address.district],
    [output.value.address.state],
    [output.value.address.postalCode],
    [output.value.address.country],
    [output.value.address.period],
    [output.value.age.id],
    [output.value.age.extension],
    [output.value.age.value],
    [output.value.age.comparator],
    [output.value.age.unit],
    [output.value.age.system],
    [output.value.age.code],
    [output.value.annotation.id],
    [output.value.annotation.extension],
    [output.value.annotation.time],
    [output.value.annotation.text],
    [output.value.annotation.author.reference],
    [output.value.annotation.author.string],
    [output.value.attachment.id],
    [output.value.attachment.extension],
    [output.value.attachment.contentType],
    [output.value.attachment.language],
    [output.value.attachment.data],
    [output.value.attachment.url],
    [output.value.attachment.size],
    [output.value.attachment.hash],
    [output.value.attachment.title],
    [output.value.attachment.creation],
    [output.value.codeableConcept.id],
    [output.value.codeableConcept.extension],
    [output.value.codeableConcept.coding],
    [output.value.codeableConcept.text],
    [output.value.coding.id],
    [output.value.coding.extension],
    [output.value.coding.system],
    [output.value.coding.version],
    [output.value.coding.code],
    [output.value.coding.display],
    [output.value.coding.userSelected],
    [output.value.contactPoint.id],
    [output.value.contactPoint.extension],
    [output.value.contactPoint.system],
    [output.value.contactPoint.value],
    [output.value.contactPoint.use],
    [output.value.contactPoint.rank],
    [output.value.contactPoint.period],
    [output.value.count.id],
    [output.value.count.extension],
    [output.value.count.value],
    [output.value.count.comparator],
    [output.value.count.unit],
    [output.value.count.system],
    [output.value.count.code],
    [output.value.distance.id],
    [output.value.distance.extension],
    [output.value.distance.value],
    [output.value.distance.comparator],
    [output.value.distance.unit],
    [output.value.distance.system],
    [output.value.distance.code],
    [output.value.duration.id],
    [output.value.duration.extension],
    [output.value.duration.value],
    [output.value.duration.comparator],
    [output.value.duration.unit],
    [output.value.duration.system],
    [output.value.duration.code],
    [output.value.humanName.id],
    [output.value.humanName.extension],
    [output.value.humanName.use],
    [output.value.humanName.text],
    [output.value.humanName.family],
    [output.value.humanName.given],
    [output.value.humanName.prefix],
    [output.value.humanName.suffix],
    [output.value.humanName.period],
    [output.value.identifier.id],
    [output.value.identifier.extension],
    [output.value.identifier.use],
    [output.value.identifier.type],
    [output.value.identifier.system],
    [output.value.identifier.value],
    [output.value.identifier.period],
    [output.value.identifier.assigner],
    [output.value.money.id],
    [output.value.money.extension],
    [output.value.money.value],
    [output.value.money.currency],
    [output.value.period.id],
    [output.value.period.extension],
    [output.value.period.start],
    [output.value.period.end],
    [output.value.quantity.id],
    [output.value.quantity.extension],
    [output.value.quantity.value],
    [output.value.quantity.comparator],
    [output.value.quantity.unit],
    [output.value.quantity.system],
    [output.value.quantity.code],
    [output.value.range.id],
    [output.value.range.extension],
    [output.value.range.low],
    [output.value.range.high],
    [output.value.ratio.id],
    [output.value.ratio.extension],
    [output.value.ratio.numerator],
    [output.value.ratio.denominator],
    [output.value.reference.id],
    [output.value.reference.extension],
    [output.value.reference.reference],
    [output.value.reference.type],
    [output.value.reference.identifier],
    [output.value.reference.display],
    [output.value.sampledData.id],
    [output.value.sampledData.extension],
    [output.value.sampledData.origin],
    [output.value.sampledData.period],
    [output.value.sampledData.factor],
    [output.value.sampledData.lowerLimit],
    [output.value.sampledData.upperLimit],
    [output.value.sampledData.dimensions],
    [output.value.sampledData.data],
    [output.value.signature.id],
    [output.value.signature.extension],
    [output.value.signature.type],
    [output.value.signature.when],
    [output.value.signature.who],
    [output.value.signature.onBehalfOf],
    [output.value.signature.targetFormat],
    [output.value.signature.sigFormat],
    [output.value.signature.data],
    [output.value.timing.id],
    [output.value.timing.extension],
    [output.value.timing.modifierExtension],
    [output.value.timing.event],
    [output.value.timing.repeat],
    [output.value.timing.code],
    [output.value.contactDetail.id],
    [output.value.contactDetail.extension],
    [output.value.contactDetail.name],
    [output.value.contactDetail.telecom],
    [output.value.contributor.id],
    [output.value.contributor.extension],
    [output.value.contributor.type],
    [output.value.contributor.name],
    [output.value.contributor.contact],
    [output.value.dataRequirement.id],
    [output.value.dataRequirement.extension],
    [output.value.dataRequirement.type],
    [output.value.dataRequirement.profile],
    [output.value.dataRequirement.mustSupport],
    [output.value.dataRequirement.codeFilter],
    [output.value.dataRequirement.dateFilter],
    [output.value.dataRequirement.limit],
    [output.value.dataRequirement.sort],
    [output.value.dataRequirement.subject.codeableConcept],
    [output.value.dataRequirement.subject.reference],
    [output.value.expression.id],
    [output.value.expression.extension],
    [output.value.expression.description],
    [output.value.expression.name],
    [output.value.expression.language],
    [output.value.expression.expression],
    [output.value.expression.reference],
    [output.value.parameterDefinition.id],
    [output.value.parameterDefinition.extension],
    [output.value.parameterDefinition.name],
    [output.value.parameterDefinition.use],
    [output.value.parameterDefinition.min],
    [output.value.parameterDefinition.max],
    [output.value.parameterDefinition.documentation],
    [output.value.parameterDefinition.type],
    [output.value.parameterDefinition.profile],
    [output.value.relatedArtifact.id],
    [output.value.relatedArtifact.extension],
    [output.value.relatedArtifact.type],
    [output.value.relatedArtifact.label],
    [output.value.relatedArtifact.display],
    [output.value.relatedArtifact.citation],
    [output.value.relatedArtifact.url],
    [output.value.relatedArtifact.document],
    [output.value.relatedArtifact.resource],
    [output.value.triggerDefinition.id],
    [output.value.triggerDefinition.extension],
    [output.value.triggerDefinition.type],
    [output.value.triggerDefinition.name],
    [output.value.triggerDefinition.data],
    [output.value.triggerDefinition.condition],
    [output.value.triggerDefinition.timing.timing],
    [output.value.triggerDefinition.timing.reference],
    [output.value.triggerDefinition.timing.date],
    [output.value.triggerDefinition.timing.dateTime],
    [output.value.usageContext.id],
    [output.value.usageContext.extension],
    [output.value.usageContext.code],
    [output.value.usageContext.value.codeableConcept],
    [output.value.usageContext.value.quantity],
    [output.value.usageContext.value.range],
    [output.value.usageContext.value.reference],
    [output.value.dosage.id],
    [output.value.dosage.extension],
    [output.value.dosage.modifierExtension],
    [output.value.dosage.sequence],
    [output.value.dosage.text],
    [output.value.dosage.additionalInstruction],
    [output.value.dosage.patientInstruction],
    [output.value.dosage.timing],
    [output.value.dosage.site],
    [output.value.dosage.route],
    [output.value.dosage.method],
    [output.value.dosage.doseAndRate],
    [output.value.dosage.maxDosePerPeriod],
    [output.value.dosage.maxDosePerAdministration],
    [output.value.dosage.maxDosePerLifetime],
    [output.value.dosage.asNeeded.boolean],
    [output.value.dosage.asNeeded.codeableConcept],
    [output.value.meta.id],
    [output.value.meta.extension],
    [output.value.meta.versionId],
    [output.value.meta.lastUpdated],
    [output.value.meta.source],
    [output.value.meta.profile],
    [output.value.meta.security],
    [output.value.meta.tag]
FROM openrowset (
        BULK 'Task/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [output.JSON]  VARCHAR(MAX) '$.output'
    ) AS rowset
    CROSS APPLY openjson (rowset.[output.JSON]) with (
        [output.id]                    NVARCHAR(100)       '$.id',
        [output.extension]             NVARCHAR(MAX)       '$.extension',
        [output.modifierExtension]     NVARCHAR(MAX)       '$.modifierExtension',
        [output.type.id]               NVARCHAR(100)       '$.type.id',
        [output.type.extension]        NVARCHAR(MAX)       '$.type.extension',
        [output.type.coding]           NVARCHAR(MAX)       '$.type.coding',
        [output.type.text]             NVARCHAR(4000)      '$.type.text',
        [output.value.base64Binary]    NVARCHAR(MAX)       '$.value.base64Binary',
        [output.value.boolean]         bit                 '$.value.boolean',
        [output.value.canonical]       VARCHAR(256)        '$.value.canonical',
        [output.value.code]            NVARCHAR(4000)      '$.value.code',
        [output.value.date]            VARCHAR(64)         '$.value.date',
        [output.value.dateTime]        VARCHAR(64)         '$.value.dateTime',
        [output.value.decimal]         float               '$.value.decimal',
        [output.value.id]              VARCHAR(64)         '$.value.id',
        [output.value.instant]         VARCHAR(64)         '$.value.instant',
        [output.value.integer]         bigint              '$.value.integer',
        [output.value.markdown]        NVARCHAR(MAX)       '$.value.markdown',
        [output.value.oid]             VARCHAR(64)         '$.value.oid',
        [output.value.positiveInt]     bigint              '$.value.positiveInt',
        [output.value.string]          NVARCHAR(4000)      '$.value.string',
        [output.value.time]            NVARCHAR(MAX)       '$.value.time',
        [output.value.unsignedInt]     bigint              '$.value.unsignedInt',
        [output.value.uri]             VARCHAR(256)        '$.value.uri',
        [output.value.url]             VARCHAR(256)        '$.value.url',
        [output.value.uuid]            NVARCHAR(MAX)       '$.value.uuid',
        [output.value.address.id]      NVARCHAR(100)       '$.value.address.id',
        [output.value.address.extension] NVARCHAR(MAX)       '$.value.address.extension',
        [output.value.address.use]     NVARCHAR(64)        '$.value.address.use',
        [output.value.address.type]    NVARCHAR(64)        '$.value.address.type',
        [output.value.address.text]    NVARCHAR(4000)      '$.value.address.text',
        [output.value.address.line]    NVARCHAR(MAX)       '$.value.address.line',
        [output.value.address.city]    NVARCHAR(500)       '$.value.address.city',
        [output.value.address.district] NVARCHAR(500)       '$.value.address.district',
        [output.value.address.state]   NVARCHAR(500)       '$.value.address.state',
        [output.value.address.postalCode] NVARCHAR(100)       '$.value.address.postalCode',
        [output.value.address.country] NVARCHAR(500)       '$.value.address.country',
        [output.value.address.period]  NVARCHAR(MAX)       '$.value.address.period',
        [output.value.age.id]          NVARCHAR(100)       '$.value.age.id',
        [output.value.age.extension]   NVARCHAR(MAX)       '$.value.age.extension',
        [output.value.age.value]       float               '$.value.age.value',
        [output.value.age.comparator]  NVARCHAR(64)        '$.value.age.comparator',
        [output.value.age.unit]        NVARCHAR(100)       '$.value.age.unit',
        [output.value.age.system]      VARCHAR(256)        '$.value.age.system',
        [output.value.age.code]        NVARCHAR(4000)      '$.value.age.code',
        [output.value.annotation.id]   NVARCHAR(100)       '$.value.annotation.id',
        [output.value.annotation.extension] NVARCHAR(MAX)       '$.value.annotation.extension',
        [output.value.annotation.time] VARCHAR(64)         '$.value.annotation.time',
        [output.value.annotation.text] NVARCHAR(MAX)       '$.value.annotation.text',
        [output.value.annotation.author.reference] NVARCHAR(MAX)       '$.value.annotation.author.reference',
        [output.value.annotation.author.string] NVARCHAR(4000)      '$.value.annotation.author.string',
        [output.value.attachment.id]   NVARCHAR(100)       '$.value.attachment.id',
        [output.value.attachment.extension] NVARCHAR(MAX)       '$.value.attachment.extension',
        [output.value.attachment.contentType] NVARCHAR(100)       '$.value.attachment.contentType',
        [output.value.attachment.language] NVARCHAR(100)       '$.value.attachment.language',
        [output.value.attachment.data] NVARCHAR(MAX)       '$.value.attachment.data',
        [output.value.attachment.url]  VARCHAR(256)        '$.value.attachment.url',
        [output.value.attachment.size] bigint              '$.value.attachment.size',
        [output.value.attachment.hash] NVARCHAR(MAX)       '$.value.attachment.hash',
        [output.value.attachment.title] NVARCHAR(4000)      '$.value.attachment.title',
        [output.value.attachment.creation] VARCHAR(64)         '$.value.attachment.creation',
        [output.value.codeableConcept.id] NVARCHAR(100)       '$.value.codeableConcept.id',
        [output.value.codeableConcept.extension] NVARCHAR(MAX)       '$.value.codeableConcept.extension',
        [output.value.codeableConcept.coding] NVARCHAR(MAX)       '$.value.codeableConcept.coding',
        [output.value.codeableConcept.text] NVARCHAR(4000)      '$.value.codeableConcept.text',
        [output.value.coding.id]       NVARCHAR(100)       '$.value.coding.id',
        [output.value.coding.extension] NVARCHAR(MAX)       '$.value.coding.extension',
        [output.value.coding.system]   VARCHAR(256)        '$.value.coding.system',
        [output.value.coding.version]  NVARCHAR(100)       '$.value.coding.version',
        [output.value.coding.code]     NVARCHAR(4000)      '$.value.coding.code',
        [output.value.coding.display]  NVARCHAR(4000)      '$.value.coding.display',
        [output.value.coding.userSelected] bit                 '$.value.coding.userSelected',
        [output.value.contactPoint.id] NVARCHAR(100)       '$.value.contactPoint.id',
        [output.value.contactPoint.extension] NVARCHAR(MAX)       '$.value.contactPoint.extension',
        [output.value.contactPoint.system] NVARCHAR(64)        '$.value.contactPoint.system',
        [output.value.contactPoint.value] NVARCHAR(4000)      '$.value.contactPoint.value',
        [output.value.contactPoint.use] NVARCHAR(64)        '$.value.contactPoint.use',
        [output.value.contactPoint.rank] bigint              '$.value.contactPoint.rank',
        [output.value.contactPoint.period] NVARCHAR(MAX)       '$.value.contactPoint.period',
        [output.value.count.id]        NVARCHAR(100)       '$.value.count.id',
        [output.value.count.extension] NVARCHAR(MAX)       '$.value.count.extension',
        [output.value.count.value]     float               '$.value.count.value',
        [output.value.count.comparator] NVARCHAR(64)        '$.value.count.comparator',
        [output.value.count.unit]      NVARCHAR(100)       '$.value.count.unit',
        [output.value.count.system]    VARCHAR(256)        '$.value.count.system',
        [output.value.count.code]      NVARCHAR(4000)      '$.value.count.code',
        [output.value.distance.id]     NVARCHAR(100)       '$.value.distance.id',
        [output.value.distance.extension] NVARCHAR(MAX)       '$.value.distance.extension',
        [output.value.distance.value]  float               '$.value.distance.value',
        [output.value.distance.comparator] NVARCHAR(64)        '$.value.distance.comparator',
        [output.value.distance.unit]   NVARCHAR(100)       '$.value.distance.unit',
        [output.value.distance.system] VARCHAR(256)        '$.value.distance.system',
        [output.value.distance.code]   NVARCHAR(4000)      '$.value.distance.code',
        [output.value.duration.id]     NVARCHAR(100)       '$.value.duration.id',
        [output.value.duration.extension] NVARCHAR(MAX)       '$.value.duration.extension',
        [output.value.duration.value]  float               '$.value.duration.value',
        [output.value.duration.comparator] NVARCHAR(64)        '$.value.duration.comparator',
        [output.value.duration.unit]   NVARCHAR(100)       '$.value.duration.unit',
        [output.value.duration.system] VARCHAR(256)        '$.value.duration.system',
        [output.value.duration.code]   NVARCHAR(4000)      '$.value.duration.code',
        [output.value.humanName.id]    NVARCHAR(100)       '$.value.humanName.id',
        [output.value.humanName.extension] NVARCHAR(MAX)       '$.value.humanName.extension',
        [output.value.humanName.use]   NVARCHAR(64)        '$.value.humanName.use',
        [output.value.humanName.text]  NVARCHAR(4000)      '$.value.humanName.text',
        [output.value.humanName.family] NVARCHAR(500)       '$.value.humanName.family',
        [output.value.humanName.given] NVARCHAR(MAX)       '$.value.humanName.given',
        [output.value.humanName.prefix] NVARCHAR(MAX)       '$.value.humanName.prefix',
        [output.value.humanName.suffix] NVARCHAR(MAX)       '$.value.humanName.suffix',
        [output.value.humanName.period] NVARCHAR(MAX)       '$.value.humanName.period',
        [output.value.identifier.id]   NVARCHAR(100)       '$.value.identifier.id',
        [output.value.identifier.extension] NVARCHAR(MAX)       '$.value.identifier.extension',
        [output.value.identifier.use]  NVARCHAR(64)        '$.value.identifier.use',
        [output.value.identifier.type] NVARCHAR(MAX)       '$.value.identifier.type',
        [output.value.identifier.system] VARCHAR(256)        '$.value.identifier.system',
        [output.value.identifier.value] NVARCHAR(4000)      '$.value.identifier.value',
        [output.value.identifier.period] NVARCHAR(MAX)       '$.value.identifier.period',
        [output.value.identifier.assigner] NVARCHAR(MAX)       '$.value.identifier.assigner',
        [output.value.money.id]        NVARCHAR(100)       '$.value.money.id',
        [output.value.money.extension] NVARCHAR(MAX)       '$.value.money.extension',
        [output.value.money.value]     float               '$.value.money.value',
        [output.value.money.currency]  NVARCHAR(100)       '$.value.money.currency',
        [output.value.period.id]       NVARCHAR(100)       '$.value.period.id',
        [output.value.period.extension] NVARCHAR(MAX)       '$.value.period.extension',
        [output.value.period.start]    VARCHAR(64)         '$.value.period.start',
        [output.value.period.end]      VARCHAR(64)         '$.value.period.end',
        [output.value.quantity.id]     NVARCHAR(100)       '$.value.quantity.id',
        [output.value.quantity.extension] NVARCHAR(MAX)       '$.value.quantity.extension',
        [output.value.quantity.value]  float               '$.value.quantity.value',
        [output.value.quantity.comparator] NVARCHAR(64)        '$.value.quantity.comparator',
        [output.value.quantity.unit]   NVARCHAR(100)       '$.value.quantity.unit',
        [output.value.quantity.system] VARCHAR(256)        '$.value.quantity.system',
        [output.value.quantity.code]   NVARCHAR(4000)      '$.value.quantity.code',
        [output.value.range.id]        NVARCHAR(100)       '$.value.range.id',
        [output.value.range.extension] NVARCHAR(MAX)       '$.value.range.extension',
        [output.value.range.low]       NVARCHAR(MAX)       '$.value.range.low',
        [output.value.range.high]      NVARCHAR(MAX)       '$.value.range.high',
        [output.value.ratio.id]        NVARCHAR(100)       '$.value.ratio.id',
        [output.value.ratio.extension] NVARCHAR(MAX)       '$.value.ratio.extension',
        [output.value.ratio.numerator] NVARCHAR(MAX)       '$.value.ratio.numerator',
        [output.value.ratio.denominator] NVARCHAR(MAX)       '$.value.ratio.denominator',
        [output.value.reference.id]    NVARCHAR(100)       '$.value.reference.id',
        [output.value.reference.extension] NVARCHAR(MAX)       '$.value.reference.extension',
        [output.value.reference.reference] NVARCHAR(4000)      '$.value.reference.reference',
        [output.value.reference.type]  VARCHAR(256)        '$.value.reference.type',
        [output.value.reference.identifier] NVARCHAR(MAX)       '$.value.reference.identifier',
        [output.value.reference.display] NVARCHAR(4000)      '$.value.reference.display',
        [output.value.sampledData.id]  NVARCHAR(100)       '$.value.sampledData.id',
        [output.value.sampledData.extension] NVARCHAR(MAX)       '$.value.sampledData.extension',
        [output.value.sampledData.origin] NVARCHAR(MAX)       '$.value.sampledData.origin',
        [output.value.sampledData.period] float               '$.value.sampledData.period',
        [output.value.sampledData.factor] float               '$.value.sampledData.factor',
        [output.value.sampledData.lowerLimit] float               '$.value.sampledData.lowerLimit',
        [output.value.sampledData.upperLimit] float               '$.value.sampledData.upperLimit',
        [output.value.sampledData.dimensions] bigint              '$.value.sampledData.dimensions',
        [output.value.sampledData.data] NVARCHAR(4000)      '$.value.sampledData.data',
        [output.value.signature.id]    NVARCHAR(100)       '$.value.signature.id',
        [output.value.signature.extension] NVARCHAR(MAX)       '$.value.signature.extension',
        [output.value.signature.type]  NVARCHAR(MAX)       '$.value.signature.type',
        [output.value.signature.when]  VARCHAR(64)         '$.value.signature.when',
        [output.value.signature.who]   NVARCHAR(MAX)       '$.value.signature.who',
        [output.value.signature.onBehalfOf] NVARCHAR(MAX)       '$.value.signature.onBehalfOf',
        [output.value.signature.targetFormat] NVARCHAR(100)       '$.value.signature.targetFormat',
        [output.value.signature.sigFormat] NVARCHAR(100)       '$.value.signature.sigFormat',
        [output.value.signature.data]  NVARCHAR(MAX)       '$.value.signature.data',
        [output.value.timing.id]       NVARCHAR(100)       '$.value.timing.id',
        [output.value.timing.extension] NVARCHAR(MAX)       '$.value.timing.extension',
        [output.value.timing.modifierExtension] NVARCHAR(MAX)       '$.value.timing.modifierExtension',
        [output.value.timing.event]    NVARCHAR(MAX)       '$.value.timing.event',
        [output.value.timing.repeat]   NVARCHAR(MAX)       '$.value.timing.repeat',
        [output.value.timing.code]     NVARCHAR(MAX)       '$.value.timing.code',
        [output.value.contactDetail.id] NVARCHAR(100)       '$.value.contactDetail.id',
        [output.value.contactDetail.extension] NVARCHAR(MAX)       '$.value.contactDetail.extension',
        [output.value.contactDetail.name] NVARCHAR(500)       '$.value.contactDetail.name',
        [output.value.contactDetail.telecom] NVARCHAR(MAX)       '$.value.contactDetail.telecom',
        [output.value.contributor.id]  NVARCHAR(100)       '$.value.contributor.id',
        [output.value.contributor.extension] NVARCHAR(MAX)       '$.value.contributor.extension',
        [output.value.contributor.type] NVARCHAR(64)        '$.value.contributor.type',
        [output.value.contributor.name] NVARCHAR(500)       '$.value.contributor.name',
        [output.value.contributor.contact] NVARCHAR(MAX)       '$.value.contributor.contact',
        [output.value.dataRequirement.id] NVARCHAR(100)       '$.value.dataRequirement.id',
        [output.value.dataRequirement.extension] NVARCHAR(MAX)       '$.value.dataRequirement.extension',
        [output.value.dataRequirement.type] NVARCHAR(100)       '$.value.dataRequirement.type',
        [output.value.dataRequirement.profile] NVARCHAR(MAX)       '$.value.dataRequirement.profile',
        [output.value.dataRequirement.mustSupport] NVARCHAR(MAX)       '$.value.dataRequirement.mustSupport',
        [output.value.dataRequirement.codeFilter] NVARCHAR(MAX)       '$.value.dataRequirement.codeFilter',
        [output.value.dataRequirement.dateFilter] NVARCHAR(MAX)       '$.value.dataRequirement.dateFilter',
        [output.value.dataRequirement.limit] bigint              '$.value.dataRequirement.limit',
        [output.value.dataRequirement.sort] NVARCHAR(MAX)       '$.value.dataRequirement.sort',
        [output.value.dataRequirement.subject.codeableConcept] NVARCHAR(MAX)       '$.value.dataRequirement.subject.codeableConcept',
        [output.value.dataRequirement.subject.reference] NVARCHAR(MAX)       '$.value.dataRequirement.subject.reference',
        [output.value.expression.id]   NVARCHAR(100)       '$.value.expression.id',
        [output.value.expression.extension] NVARCHAR(MAX)       '$.value.expression.extension',
        [output.value.expression.description] NVARCHAR(4000)      '$.value.expression.description',
        [output.value.expression.name] VARCHAR(64)         '$.value.expression.name',
        [output.value.expression.language] NVARCHAR(64)        '$.value.expression.language',
        [output.value.expression.expression] NVARCHAR(4000)      '$.value.expression.expression',
        [output.value.expression.reference] VARCHAR(256)        '$.value.expression.reference',
        [output.value.parameterDefinition.id] NVARCHAR(100)       '$.value.parameterDefinition.id',
        [output.value.parameterDefinition.extension] NVARCHAR(MAX)       '$.value.parameterDefinition.extension',
        [output.value.parameterDefinition.name] NVARCHAR(500)       '$.value.parameterDefinition.name',
        [output.value.parameterDefinition.use] NVARCHAR(100)       '$.value.parameterDefinition.use',
        [output.value.parameterDefinition.min] bigint              '$.value.parameterDefinition.min',
        [output.value.parameterDefinition.max] NVARCHAR(100)       '$.value.parameterDefinition.max',
        [output.value.parameterDefinition.documentation] NVARCHAR(4000)      '$.value.parameterDefinition.documentation',
        [output.value.parameterDefinition.type] NVARCHAR(100)       '$.value.parameterDefinition.type',
        [output.value.parameterDefinition.profile] VARCHAR(256)        '$.value.parameterDefinition.profile',
        [output.value.relatedArtifact.id] NVARCHAR(100)       '$.value.relatedArtifact.id',
        [output.value.relatedArtifact.extension] NVARCHAR(MAX)       '$.value.relatedArtifact.extension',
        [output.value.relatedArtifact.type] NVARCHAR(64)        '$.value.relatedArtifact.type',
        [output.value.relatedArtifact.label] NVARCHAR(100)       '$.value.relatedArtifact.label',
        [output.value.relatedArtifact.display] NVARCHAR(4000)      '$.value.relatedArtifact.display',
        [output.value.relatedArtifact.citation] NVARCHAR(MAX)       '$.value.relatedArtifact.citation',
        [output.value.relatedArtifact.url] VARCHAR(256)        '$.value.relatedArtifact.url',
        [output.value.relatedArtifact.document] NVARCHAR(MAX)       '$.value.relatedArtifact.document',
        [output.value.relatedArtifact.resource] VARCHAR(256)        '$.value.relatedArtifact.resource',
        [output.value.triggerDefinition.id] NVARCHAR(100)       '$.value.triggerDefinition.id',
        [output.value.triggerDefinition.extension] NVARCHAR(MAX)       '$.value.triggerDefinition.extension',
        [output.value.triggerDefinition.type] NVARCHAR(64)        '$.value.triggerDefinition.type',
        [output.value.triggerDefinition.name] NVARCHAR(500)       '$.value.triggerDefinition.name',
        [output.value.triggerDefinition.data] NVARCHAR(MAX)       '$.value.triggerDefinition.data',
        [output.value.triggerDefinition.condition] NVARCHAR(MAX)       '$.value.triggerDefinition.condition',
        [output.value.triggerDefinition.timing.timing] NVARCHAR(MAX)       '$.value.triggerDefinition.timing.timing',
        [output.value.triggerDefinition.timing.reference] NVARCHAR(MAX)       '$.value.triggerDefinition.timing.reference',
        [output.value.triggerDefinition.timing.date] VARCHAR(64)         '$.value.triggerDefinition.timing.date',
        [output.value.triggerDefinition.timing.dateTime] VARCHAR(64)         '$.value.triggerDefinition.timing.dateTime',
        [output.value.usageContext.id] NVARCHAR(100)       '$.value.usageContext.id',
        [output.value.usageContext.extension] NVARCHAR(MAX)       '$.value.usageContext.extension',
        [output.value.usageContext.code] NVARCHAR(MAX)       '$.value.usageContext.code',
        [output.value.usageContext.value.codeableConcept] NVARCHAR(MAX)       '$.value.usageContext.value.codeableConcept',
        [output.value.usageContext.value.quantity] NVARCHAR(MAX)       '$.value.usageContext.value.quantity',
        [output.value.usageContext.value.range] NVARCHAR(MAX)       '$.value.usageContext.value.range',
        [output.value.usageContext.value.reference] NVARCHAR(MAX)       '$.value.usageContext.value.reference',
        [output.value.dosage.id]       NVARCHAR(100)       '$.value.dosage.id',
        [output.value.dosage.extension] NVARCHAR(MAX)       '$.value.dosage.extension',
        [output.value.dosage.modifierExtension] NVARCHAR(MAX)       '$.value.dosage.modifierExtension',
        [output.value.dosage.sequence] bigint              '$.value.dosage.sequence',
        [output.value.dosage.text]     NVARCHAR(4000)      '$.value.dosage.text',
        [output.value.dosage.additionalInstruction] NVARCHAR(MAX)       '$.value.dosage.additionalInstruction',
        [output.value.dosage.patientInstruction] NVARCHAR(4000)      '$.value.dosage.patientInstruction',
        [output.value.dosage.timing]   NVARCHAR(MAX)       '$.value.dosage.timing',
        [output.value.dosage.site]     NVARCHAR(MAX)       '$.value.dosage.site',
        [output.value.dosage.route]    NVARCHAR(MAX)       '$.value.dosage.route',
        [output.value.dosage.method]   NVARCHAR(MAX)       '$.value.dosage.method',
        [output.value.dosage.doseAndRate] NVARCHAR(MAX)       '$.value.dosage.doseAndRate',
        [output.value.dosage.maxDosePerPeriod] NVARCHAR(MAX)       '$.value.dosage.maxDosePerPeriod',
        [output.value.dosage.maxDosePerAdministration] NVARCHAR(MAX)       '$.value.dosage.maxDosePerAdministration',
        [output.value.dosage.maxDosePerLifetime] NVARCHAR(MAX)       '$.value.dosage.maxDosePerLifetime',
        [output.value.dosage.asNeeded.boolean] bit                 '$.value.dosage.asNeeded.boolean',
        [output.value.dosage.asNeeded.codeableConcept] NVARCHAR(MAX)       '$.value.dosage.asNeeded.codeableConcept',
        [output.value.meta.id]         NVARCHAR(100)       '$.value.meta.id',
        [output.value.meta.extension]  NVARCHAR(MAX)       '$.value.meta.extension',
        [output.value.meta.versionId]  VARCHAR(64)         '$.value.meta.versionId',
        [output.value.meta.lastUpdated] VARCHAR(64)         '$.value.meta.lastUpdated',
        [output.value.meta.source]     VARCHAR(256)        '$.value.meta.source',
        [output.value.meta.profile]    NVARCHAR(MAX)       '$.value.meta.profile',
        [output.value.meta.security]   NVARCHAR(MAX)       '$.value.meta.security',
        [output.value.meta.tag]        NVARCHAR(MAX)       '$.value.meta.tag'
    ) j
