CREATE EXTERNAL TABLE [fhir].[InventoryReport] (
    [resourceType] NVARCHAR(4000),
    [id] VARCHAR(64),
    [meta.id] NVARCHAR(100),
    [meta.extension] NVARCHAR(MAX),
    [meta.versionId] VARCHAR(64),
    [meta.lastUpdated] VARCHAR(64),
    [meta.source] VARCHAR(256),
    [meta.profile] VARCHAR(MAX),
    [meta.security] VARCHAR(MAX),
    [meta.tag] VARCHAR(MAX),
    [implicitRules] VARCHAR(256),
    [language] NVARCHAR(100),
    [text.id] NVARCHAR(100),
    [text.extension] NVARCHAR(MAX),
    [text.status] NVARCHAR(64),
    [text.div] NVARCHAR(MAX),
    [extension] NVARCHAR(MAX),
    [modifierExtension] NVARCHAR(MAX),
    [identifier] VARCHAR(MAX),
    [status] NVARCHAR(100),
    [countType] NVARCHAR(4000),
    [operationType.id] NVARCHAR(100),
    [operationType.extension] NVARCHAR(MAX),
    [operationType.coding] VARCHAR(MAX),
    [operationType.text] NVARCHAR(4000),
    [operationTypeReason.id] NVARCHAR(100),
    [operationTypeReason.extension] NVARCHAR(MAX),
    [operationTypeReason.coding] VARCHAR(MAX),
    [operationTypeReason.text] NVARCHAR(4000),
    [reportedDateTime] VARCHAR(64),
    [reporter.id] NVARCHAR(100),
    [reporter.extension] NVARCHAR(MAX),
    [reporter.reference] NVARCHAR(4000),
    [reporter.type] VARCHAR(256),
    [reporter.identifier.id] NVARCHAR(100),
    [reporter.identifier.extension] NVARCHAR(MAX),
    [reporter.identifier.use] NVARCHAR(64),
    [reporter.identifier.type] NVARCHAR(MAX),
    [reporter.identifier.system] VARCHAR(256),
    [reporter.identifier.value] NVARCHAR(4000),
    [reporter.identifier.period] NVARCHAR(MAX),
    [reporter.identifier.assigner] NVARCHAR(MAX),
    [reporter.display] NVARCHAR(4000),
    [reportingPeriod.id] NVARCHAR(100),
    [reportingPeriod.extension] NVARCHAR(MAX),
    [reportingPeriod.start] VARCHAR(64),
    [reportingPeriod.end] VARCHAR(64),
    [inventoryListing] VARCHAR(MAX),
    [note.id] NVARCHAR(100),
    [note.extension] NVARCHAR(MAX),
    [note.time] VARCHAR(64),
    [note.text] NVARCHAR(MAX),
    [note.author.reference.id] NVARCHAR(100),
    [note.author.reference.extension] NVARCHAR(MAX),
    [note.author.reference.reference] NVARCHAR(4000),
    [note.author.reference.type] VARCHAR(256),
    [note.author.reference.identifier] NVARCHAR(MAX),
    [note.author.reference.display] NVARCHAR(4000),
    [note.author.string] NVARCHAR(4000),
) WITH (
    LOCATION='/InventoryReport/**',
    DATA_SOURCE = ParquetSource,
    FILE_FORMAT = ParquetFormat
);

GO

CREATE VIEW fhir.InventoryReportIdentifier AS
SELECT
    [id],
    [identifier.JSON],
    [identifier.id],
    [identifier.extension],
    [identifier.use],
    [identifier.type.id],
    [identifier.type.extension],
    [identifier.type.coding],
    [identifier.type.text],
    [identifier.system],
    [identifier.value],
    [identifier.period.id],
    [identifier.period.extension],
    [identifier.period.start],
    [identifier.period.end],
    [identifier.assigner.id],
    [identifier.assigner.extension],
    [identifier.assigner.reference],
    [identifier.assigner.type],
    [identifier.assigner.identifier],
    [identifier.assigner.display]
FROM openrowset (
        BULK 'InventoryReport/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [identifier.JSON]  VARCHAR(MAX) '$.identifier'
    ) AS rowset
    CROSS APPLY openjson (rowset.[identifier.JSON]) with (
        [identifier.id]                NVARCHAR(100)       '$.id',
        [identifier.extension]         NVARCHAR(MAX)       '$.extension',
        [identifier.use]               NVARCHAR(64)        '$.use',
        [identifier.type.id]           NVARCHAR(100)       '$.type.id',
        [identifier.type.extension]    NVARCHAR(MAX)       '$.type.extension',
        [identifier.type.coding]       NVARCHAR(MAX)       '$.type.coding',
        [identifier.type.text]         NVARCHAR(4000)      '$.type.text',
        [identifier.system]            VARCHAR(256)        '$.system',
        [identifier.value]             NVARCHAR(4000)      '$.value',
        [identifier.period.id]         NVARCHAR(100)       '$.period.id',
        [identifier.period.extension]  NVARCHAR(MAX)       '$.period.extension',
        [identifier.period.start]      VARCHAR(64)         '$.period.start',
        [identifier.period.end]        VARCHAR(64)         '$.period.end',
        [identifier.assigner.id]       NVARCHAR(100)       '$.assigner.id',
        [identifier.assigner.extension] NVARCHAR(MAX)       '$.assigner.extension',
        [identifier.assigner.reference] NVARCHAR(4000)      '$.assigner.reference',
        [identifier.assigner.type]     VARCHAR(256)        '$.assigner.type',
        [identifier.assigner.identifier] NVARCHAR(MAX)       '$.assigner.identifier',
        [identifier.assigner.display]  NVARCHAR(4000)      '$.assigner.display'
    ) j

GO

CREATE VIEW fhir.InventoryReportInventoryListing AS
SELECT
    [id],
    [inventoryListing.JSON],
    [inventoryListing.id],
    [inventoryListing.extension],
    [inventoryListing.modifierExtension],
    [inventoryListing.location.id],
    [inventoryListing.location.extension],
    [inventoryListing.location.reference],
    [inventoryListing.location.type],
    [inventoryListing.location.identifier],
    [inventoryListing.location.display],
    [inventoryListing.itemStatus.id],
    [inventoryListing.itemStatus.extension],
    [inventoryListing.itemStatus.coding],
    [inventoryListing.itemStatus.text],
    [inventoryListing.countingDateTime],
    [inventoryListing.items]
FROM openrowset (
        BULK 'InventoryReport/**',
        DATA_SOURCE = 'ParquetSource',
        FORMAT = 'PARQUET'
    ) WITH (
        [id]   VARCHAR(64),
       [inventoryListing.JSON]  VARCHAR(MAX) '$.inventoryListing'
    ) AS rowset
    CROSS APPLY openjson (rowset.[inventoryListing.JSON]) with (
        [inventoryListing.id]          NVARCHAR(100)       '$.id',
        [inventoryListing.extension]   NVARCHAR(MAX)       '$.extension',
        [inventoryListing.modifierExtension] NVARCHAR(MAX)       '$.modifierExtension',
        [inventoryListing.location.id] NVARCHAR(100)       '$.location.id',
        [inventoryListing.location.extension] NVARCHAR(MAX)       '$.location.extension',
        [inventoryListing.location.reference] NVARCHAR(4000)      '$.location.reference',
        [inventoryListing.location.type] VARCHAR(256)        '$.location.type',
        [inventoryListing.location.identifier] NVARCHAR(MAX)       '$.location.identifier',
        [inventoryListing.location.display] NVARCHAR(4000)      '$.location.display',
        [inventoryListing.itemStatus.id] NVARCHAR(100)       '$.itemStatus.id',
        [inventoryListing.itemStatus.extension] NVARCHAR(MAX)       '$.itemStatus.extension',
        [inventoryListing.itemStatus.coding] NVARCHAR(MAX)       '$.itemStatus.coding',
        [inventoryListing.itemStatus.text] NVARCHAR(4000)      '$.itemStatus.text',
        [inventoryListing.countingDateTime] VARCHAR(64)         '$.countingDateTime',
        [inventoryListing.items]       NVARCHAR(MAX)       '$.items' AS JSON
    ) j
