steps:
- task: DotNetCoreCLI@2
  displayName: Build Engine Core
  inputs:
    command: build
    projects: FhirToCdm/*.sln
    arguments: '--configuration $(buildConfiguration)'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true

- task: Npm@1
  displayName: Install & Build Configuartion Generator
  inputs:
    command: ci
    workingDir: FhirToCdm/Configuration-Generator

- task: Npm@1
  displayName: Run Configuartion Generator Tests
  inputs:
    command: custom
    workingDir: FhirToCdm/Configuration-Generator
    customCommand: test --runInBand

- task: DotNetCoreCLI@2
  displayName: Run Engine Core Tests
  inputs:
    command: test
    projects: '**/Microsoft.Health.Fhir.*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-RESULTS.xml'