steps:
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.11'
  inputs:
    versionSpec: 5.11

- task: NuGetCommand@2
  displayName: 'NuGet restore packages.config'
  inputs:
    restoreSolution: '**/*.Native/packages.config'
    vstsFeed: 'FhirAnalytics/FhirAnalyticsPublic'
    restoreDirectory: '../../packages'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore solution'
  inputs:
    command: restore
    projects: FhirToDataLake/*.sln

- task: MSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: FhirToDataLake/*.sln
    msbuildArchitecture: $(buildPlatform)
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '-p:ApplicationVersion=$(version)'

# ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops#error-publish-using-zip-deploy-option-is-not-supported-for-msbuild-package-type
- task: MSBuild@1
  displayName: 'Publish function app'
  inputs:
    solution: FhirToDataLake/**/*.FunctionApp.csproj
    msbuildArchitecture: $(BuildPlatform)
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '-p:DeployOnBuild=true -p:DeployDefaultTarget=WebPublish -p:WebPublishMethod=FileSystem -p:DeleteExistingFiles=True -p:publishUrl=$(Build.SourcesDirectory)/bin/publish/functionapp -p:ApplicationVersion=$(version)'

- task: ArchiveFiles@2
  displayName: 'Archive function app'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/bin/publish/functionapp'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/FhirToDataLake/Microsoft.Health.Fhir.Synapse.FunctionApp.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/FhirToDataLake'
    ArtifactName: FhirToDataLakeBuild